### PR TITLE
ESOS+ESMM Changes 2

### PR DESCRIPTION
**Pull request by maxlk96**
## Description of changes

- ESOS and ESMM border corrected
- Delegated areas corrected
  - ESMM-EDWW/UU
  - ESMM-EPWW

## Reason and motivation

- No more pilots asking to go to UNICOM before leaving ESMM AoR

## Approved contributior?

- [ ] I am on the approved contributers list
- [ ] I have sent an request by email to get approved
- [X] Someone on the approved contributer list will review this request

### CODE REVIEW

**Comment by Adrian2k** [comment]
File is in conflict with earlier change in Norway for ENBD...

Will look at later

**Comment by maxlk96** [comment]
Solved the conflict, when can this be expected to be pushed?

**Comment by Adrian2k** [comment]
image

Border not synced up with new ENBD/ESOS border which follows delegated airspaces.

**Comment by Adrian2k** [comment]
Conflict one again - I will make a new pull request for this because now the whole file is showing as a conflict.

**Pull request closed without merging**
