### PR TITLE
VCL Sectorisation (Conflict fixing)

### PR DESCRIPTION
**Pull request by amosngSP**
conflict fixing for #324

### CODE REVIEW

**Comment by Adrian2k** [comment]
Just to confirm, is this PR supposed to replace the #300 PR?

**Comment by amosngSP** [comment]
> Just to confirm, is this PR supposed to replace the #300 PR?

Affirm

**Comment by ClipperWings** [comment]
Gentlemen,

While I can understand your view, since we will be talking statistics. India, China, Middle East and some parts of South America have a split sector. 
My humble understanding is it's per the vACC _discretion_ to use and update and we sure do want to push for all available. The files you have and it's a simple click to add them in.

When was the last time OIIX 9 sectors were staffed (except for events, yet, they are shown?) Or VECC-B, VEBN, ZXLY, ZSOF, ZYTL all of these are split sectors are shown. I am disappointed you believe it useless. We wish to grow and show the VATSIM (especially the VATSPY) community that we are a growing vACC. And duing events we do have our splits open! Nothing better than a direct picture instead of having to copy a URL and paste it. It removes this process.

I remain available for any future developments.
-David

**Comment by amosngSP** [comment]
New updates:
Added KUL to both WMKK and WMFC

**Review by NelisV — APPROVED** [review]
Looks good, would be nice if you could have a look at the border between ZJSY and VVHN in the future.

**Review by nharasym — APPROVED** [review]

**Comment by amosngSP** [comment]
Hey @NelisV , will take a look haha. Seems like i didnt catch all of the border errors

**Pull request merged**
