### PR TITLE
UEEE FIX

### PR DESCRIPTION
**Pull request by Soofushka**

### CODE REVIEW

**Comment by Soofushka** [comment]
@NelisV @Adrian2k

**Review by NelisV — CHANGES_REQUESTED** [review]
This seems to also change some things in europe, please remove if it isn't intended.

**Comment by Soofushka** [comment]
@NelisV nothing changed in european part, only changes for UEEE

**Comment by NelisV** [comment]
> @NelisV nothing changed in european part, only changes for UEEE

in that case you need to rebase this, as this pr would overwrite changes made in the past few weeks. See files changed

**Comment by Soofushka** [comment]
fixed

**Review by NelisV — CHANGES_REQUESTED** [review]
image

**Pull request closed without merging**
