### PR TITLE
RU-ERC fix + delete UHPP FIR

### PR DESCRIPTION
**Pull request by theShpuntik**

### CODE REVIEW

**Comment by NelisV** [comment]
https://github.com/vatsimnetwork/vatspy-data-project/pull/587#issuecomment-1268278981

**Review by Adrian2k — CHANGES_REQUESTED** [review]
Airports witch has UHPP as their FIR needs to be assigned a different FIR

UHPA|Pakhachi|60.553|169.103||UHPP|0 ; io
UHPD|Ossora|59.223|163.063||UHPP|0 ; io
UHPG|Tigil|57.783|158.733||UHPP|0 ; io
UHPL|Palana|59.082|159.888||UHPP|0 ; io
UHPM|Milkovo|54.68|158.547||UHPP|0 ; io
UHPN|Manily|62.485|165.337||UHPP|0 ; io
UHPP|Petropavlovsk-Kamchatskiy (Yelizovo)|53.17|158.451667||UHPP|0
UHPU|Ust-Khayryuzovo|57.1|156.735||UHPP|0 ; io
XHPL|Klyuchi-Kamchatskiye|56.31|160.802||UHPP|0 ; io

**Review by theShpuntik — COMMENTED** [review]
airports fixed

**Comment by theShpuntik** [comment]
hello?

**Review by theShpuntik — COMMENTED** [review]
Fixed this moment

**Review by Adrian2k — APPROVED** [review]

**Comment by Adrian2k** [comment]
To be merged after #587 is merged.

**Pull request closed without merging**
