### PR TITLE
Requested UUWV changes

### PR DESCRIPTION
**Pull request by dsolesvik**

### CODE REVIEW

**Comment by alex155191** [comment]
> 
> 
> > Approved. Maxim Tsygankov 1264756. VATRUS4
> 
> I can not see your account on the approved list. Have you sent an email to Nestor as described on the front page of the project?



> 
> 
> > Approved. Maxim Tsygankov 1264756. VATRUS4
> 
> I can not see your account on the approved list. Have you sent an email to Nestor as described on the front page of the project?

We're trying, but he has auto answer in the email

**Comment by prryplatypus** [comment]
I recommend reading the contents of the autoreply email. It's there on purpose 😝 
Autoreply

**Comment by alex155191** [comment]
> I recommend reading the contents of the autoreply email. It's there on purpose 😝
> Autoreply

We understand. But what should we do? We cant upload major update from March

1144030 Aleksei, Moscow FIR Instructor

**Comment by prryplatypus** [comment]
Latest email I have received and haven't replied to is from 17th September, so it's been only 3 days since I last replied to everyone. Maxim's email will be the first one I reply to next (received 3 days ago).

**Comment by alex155191** [comment]
> Latest email I have received and haven't replied to is from 17th September, so it's been only 3 days since I last replied to everyone. Maxim's email will be the first one I reply to next (received 3 days ago).

Oh! Nestor is you :) 

Thanks a lot! We will wait for reply to Maxim

**Comment by Jhenya5** [comment]
Hello, everyone. I'd like to approve it and tell one thing that VATRUS's changes are quite hard to be implemented into the update.
Gentlemen, I'd like to have a short talk to the responsible persons on the issue.
Sincerely,
Evgeny, VATRUS1

**Comment by alex155191** [comment]
@Adrian2k 
Hello everyone! Jhenya5 862634 is authorized member and his confirmation message is above

**Review by Adrian2k — APPROVED** [review]

**Comment by alex155191** [comment]
Txh. And how we can collect the second approval? 

Evgeny (Jhenya5 862634) is currently the only one authorized member from our division.

1144030 Aleksei, Moscow FIR Instructor

**Comment by prryplatypus** [comment]
Just be patient and stop asking, please. We've already seen Evgeny's apprival: that's why it's gotten an approval from Adrian. Now, when one of the others in the team is free, they'll check it too and if everything's correct, they'll merge it. It will be done for next AIRAC cycle.

**Review by NelisV — APPROVED** [review]

**Pull request merged**
