### PR TITLE
Updated Scandinavian sectors + Imported 7000+ airports/airfields from EuroControl's database

### PR DESCRIPTION
**Pull request by Adrian2k**

### CODE REVIEW

**Comment by Adrian2k** [comment]
Done.

**Comment by Adrian2k** [comment]
Sorry about that, had forgotten to remove those who are duplicated in EuroControl database. The remaining dupes are entries that was dupe already, most of them seems to be there to allow for multiple logon callsigns. I do not want to touch those.

Updated the file once again.

**Comment by Adrian2k** [comment]
Entries that were dupe from the EuroControl database is resolved now. 
Dupes that already existed is not touched as most of them seem to have a reason for being duped.

**Comment by nepetadosmil** [comment]
Thank you very much sir! :)

**Pull request merged**
