### PR TITLE
WIIF and WIIF-E Border Fix

### PR DESCRIPTION
**Pull request by arisandii**

### CODE REVIEW

**Comment by NelisV** [comment]
I'll review this, before i dive in. have you verified your github account as described in the readme?

**Comment by arisandii** [comment]
> I'll review this, before i dive in. have you verified your github account as described in the readme?

thank you. yes I already did it long time ago.

**Review by Adrian2k — CHANGES_REQUESTED** [review]
@NelisV may find other borders that are not alligned, but as a first look I can see these two borders not being correctly alligned.

image

**Comment by Adrian2k** [comment]
> > I'll review this, before i dive in. have you verified your github account as described in the readme?
> 
> thank you. yes I already did it long time ago.

Your account is not on our list of approved accounts. Can you try again?

**Comment by arisandii** [comment]
> > > I'll review this, before i dive in. have you verified your github account as described in the readme?
> > 
> > 
> > thank you. yes I already did it long time ago.
> 
> Your account is not on our list of approved accounts. Can you try again?

done

**Review by NelisV — CHANGES_REQUESTED** [review]
3 gaps you could still fix, if you can that would be great!
image

**Comment by arisandii** [comment]
Border between WAAF, RPHI, KZAK also updated based on current AIRAC.
image

**Review by NelisV — APPROVED** [review]
Looks good!

**Review by Adrian2k — APPROVED** [review]

**Pull request merged**
