### PR TITLE
Fix Anchorage FIR boundaries and subdivisions between oceanic/domestic

### PR DESCRIPTION
**Pull request by dhawton**
## Description of changes
Split up PAZA between the two oceanic airspaces and the domestic. It does include a slight fix to the KZAK and UHMM adjacent boundaries so there is no weird overlaps

## Reason and motivation
For the longest time, people logging in to ANC_??_CTR would be shown as covering the oceanic airspaces as well, and neither oceanic position was ever displayed, which causes a tremendous amount of confusion with pilots. This splits off the oceanic and domestic sectors to display appropriately and adds Oceanic positions to display when they are on.

## Approved contributior?

- [ ] I am on the approved contributers list
- [ ] I have sent an request by email to get approved
- [X] Someone on the approved contributer list will review this request

### CODE REVIEW

**Comment by Adrian2k** [comment]
Awaiting someone's approval on this first before reviewing.

**Comment by dhawton** [comment]
What staff approval is needed? The Oceanic airspace has been separated for well over a decade, it has just never been properly displayed. It can also be seen on sectionals. It can also be seen here: https://sops.zanartcc.org/docs/enroute/

**Comment by Adrian2k** [comment]
> What staff approval is needed? The Oceanic airspace has been separated for well over a decade, it has just never been properly displayed. It can also be seen on sectionals. It can also be seen here: https://sops.zanartcc.org/docs/enroute/

Any changes to the projection of FIR's require a staff member to approve the changes. 
This is to avoid members randomly changing the appearance of FIR's in their home VACC/ARTCC to something else without the approval from staff.

This is a standard practise we have had for all other countries on VATSIM and it applies for the US aswell, regardless if is been like this for years. It is as simple as an staff members sending in a request for their github account to be approved and then they commenting here that they approve of these changes.

**Comment by dhawton** [comment]
What staff member?

**Comment by dhawton** [comment]
I've sent an email, I'm the head of the Anchorage FIR in VATUSA.

**Review by NelisV — APPROVED** [review]

**Pull request merged**
