### PR TITLE
UHHH border fix and new sectors add

### PR DESCRIPTION
**Pull request by Flynn683**
## Description of changes
Fix border according to new chart
Add sectors according to VATRUS map https://vatrus.info/geo/fir/UHHH

## Reason and motivation
We will use all sectors in our future events

## Approved contributor?
- [x] I am on the approved contributors list
- [ ] I have sent an request by email to get approved
- [ ] Someone on the approved contributor list will review this request

image

### CODE REVIEW

**Comment by NelisV** [comment]
Dear @Flynn683 we would need some additional information to  add you to the approved contributors list, your email adress for instace, Can you email us?

**Review by NelisV — CHANGES_REQUESTED** [review]
Also in it's current state i'm unable to open this, seems like invalid geojson. Please check if you can open this in QGIS locally for instance.

**Review by ziplock1 — CHANGES_REQUESTED** [review]
image

Borders with other FIRs must be fixed from UHHH side, or VATJPN and VATPRC input required

**Review by ziplock1 — APPROVED** [review]
Changes looks good to me now. Thanks for your contribution!

**Comment by ziplock1** [comment]
@Flynn683 and don't forget to email via vatspy-data-project@vatsim.net

**Review by NelisV — CHANGES_REQUESTED** [review]
This is currently not valid GeoJSON. Can you try to open in QGIS or validate in some other way and fix?

**Review by NelisV — APPROVED** [review]

**Pull request merged**
