### PR TITLE
France sector description change

### PR DESCRIPTION
**Pull request by Iwhite67**
LFEE|Reims (Covers North-East LFFF FL195+)||LFEE ---> LFEE|Reims (Covers North-East LFFF FL295+)||LFEE

LFRR-E|Brest East (Covers West LFFF FL195+)||LFRR-E ---> LFRR-E|Brest East (Covers West LFFF FL295+)||LFRR-E

### CODE REVIEW

**Comment by Adrian2k** [comment]
Hi. Are you a staff member within France? If so, have you sent an email to Nestor as described on the front page of the project?

**Comment by Iwhite67** [comment]
Hello, negatif


_________________________

Alexis Zaun
Technicien SAV Nord Est

FOM Industrie FRANCE

***@***.******@***.***>
(+33) 06 40 62 82 45
________________________________

**Comment by Adrian2k** [comment]
We will need an authorised staff member from France to approve this first as per our policy.

@FrenchGap is currently the only one on this list.

**Comment by FrenchGap** [comment]
Hello there, I hereby approve the changes requested by @Iwhite67 .

Thanks @Adrian2k in advance for merging them in!

**Review by Adrian2k — APPROVED** [review]

**Review by prryplatypus — APPROVED** [review]

**Pull request merged**
