### PR TITLE
Requested FASA_CTR addition

### PR DESCRIPTION
**Pull request by dsolesvik**
image

### CODE REVIEW

**Review by Adrian2k — APPROVED** [review]
I assume the border align correctly by now.

**Comment by dsolesvik** [comment]
> I assume the border align correctly by now.

Was it unaligned?

**Comment by Adrian2k** [comment]
> > I assume the border align correctly by now.
> 
> Was it unaligned?

No what I meant I assume that the PR's you make have alligned borders now. Usually I wait until @NelisV has checked and approve it when it comes to FIRboundaries.

**Comment by dsolesvik** [comment]
> > > I assume the border align correctly by now.
> > 
> > 
> > Was it unaligned?
> 
> No what I meant I assume that the PR's you make have alligned borders now. Usually I wait until @NelisV has checked and approve it when it comes to FIRboundaries.

Oh, haha. Yeah, I do my best and QGIS is really helpful in that sense. Either way, I'll be doing another final sweep of polygon fixes once all current PRs are pushed, just to be sure.

**Review by NelisV — APPROVED** [review]

**Pull request merged**
