### PR TITLE
Sectorisation South-East Asia

### PR DESCRIPTION
**Pull request by ClipperWings**
Ho Chi Minh, Hanoi, Cambodia sectorisation. Fixed overlapping issues fixed with neighboring sectors. Mekong Radar has its own FIR

### CODE REVIEW

**Comment by Adrian2k** [comment]
Is there a need for so many splits to be shown for Vietnam? Is it a common occurrence that only part of Vietnam is controlled?

**Comment by amosngSP** [comment]
Hi @Adrian2k 
(My account is not yet verified but I'll sort that out soon. I'm a staff member of VCL)
David's kind of busy at the moment, but I've checked in with our Director and he'd like to have the individual sectorisation shown in vatspy, especially for Mekong Radar (shown in vatSPY as VVCL, but alias to VCL), as Mekong Radar covers top-down for the 4 FIRs.

**Comment by ClipperWings** [comment]
Hello, yes it is required for us in Vietnam as Sectors are and can be individually opened.

**Review by NelisV — CHANGES_REQUESTED** [review]
I'm not sure if we should want to display this many splits in this case. Looking at the usage of the callsigns over the past year we should not want to split this up in more than 3 or 4 sectors. 
image
image

Having so many splits that are not used will lead to a lot of clutter and make it more confusing for pilots to use. There also seems to be a rounding error, a lot of unnecessary 0's.

**Comment by Adrian2k** [comment]
New PR #330

**Pull request closed without merging**
