### PR TITLE
Create FIRBoundaries(VATRUS).dat

### PR DESCRIPTION
**Pull request by IvanSkatov**
VATRUS data update. Mostly FIRs consolidation, ICAO codes changes, Boundaries refinement

### CODE REVIEW

**Comment by IvanSkatov** [comment]
UWWW is the last FIR. It should be nothing after it

**Comment by nepetadosmil** [comment]
YARA
YASP
YWOL
YBKE
YDOS
YESP
YORE
YIND
YISA
YMDE
YSNO
YTAS
YTBD
YTBP
YTRT
YTSN
YARM
YAUG
YBAR
YGTH
YBIK
YKAT
YBIL
YBUR
YCOL
YCRS
YCVN
YELW
YFLD
YFOR
YGEL
YGRN
YGVE
YHUM
YHWE
YHYD
YINE
YINS
YJAR
YKEN
YKIY
YKPL
YLEA
YMLD
YMOR
YMUN
YOCN
YOXL
YPIY
YSDY
YSWY
YSTR
YTFR
YWAR
YWEG
YWON
YWRA
YYWE
ZBPE
ZHCC
ZHHH
ZHWH
ZGZU
ZJSA
ZKKP
ZLHW
ZPKM
ZSHA
ZWUQ
ZYSH
ZMBZ
?

**Comment by IvanSkatov** [comment]
In master file it is also the last

**Comment by IvanSkatov** [comment]
UAAA goes right after ZMBZ

**Comment by nepetadosmil** [comment]
It is the last one in your fork, but not in this repository. Have a look at this line and everything after; that's what is being removed in your PR: https://github.com/vatsimnetwork/vatspy-data-project/blob/master/FIRBoundaries.dat#L25015

**Comment by IvanSkatov** [comment]
I got. How can I make changes?

**Pull request closed without merging**
