### PR TITLE
Rename of several Italian APP positions

### PR DESCRIPTION
**Pull request by mferraroni**
Need to rename several Italian APP positions due to position name changes:
LIPX_APP becomes LIMM_ES0_APP
LIPQ_APP becomes LIPP_CE0_APP
LIEO_APP becomes LIRR_EW0_APP
LICA_APP becomes LIRR_ES0_APP
LIBR_APP becomes LIBB_CS0_APP

### CODE REVIEW

**Comment by mferraroni** [comment]
Hello, we are still waiting for name change approval from Jonas Kuster so please don't merge this PR until it will be makred "ready for review".

@Adrian2k I have a question, on Milano Malpensa we will need the following changes:
LIMM_W_APP becomes LIMM_ASW_APP
LIMM_E_APP becomes LIMM_ADE_APP
LIMM_N_APP becomes LIMM_ANE_APP
LIMC_F_APP becomes LIMC_MAR_APP
but my guess is that the following line will match both LIMM_*_APP and LIMC_*_APP is that correct?
`LIMC|Milano-Malpensa|45.6299|8.723094|LIMM|LIMM|0`

**Comment by Adrian2k** [comment]
```
LIPX_APP becomes LIMM_ES0_APP
LIPQ_APP becomes LIPP_CE0_APP
LIEO_APP becomes LIRR_EW0_APP
LICA_APP becomes LIRR_ES0_APP
LIBR_APP becomes LIBB_CS0_APP
```

Without going too much into details, this is not possible. I also fail to see why you would even want to use for example LIRR on two different airports when you already have a perfectly fine setup already with LIEO_APP and LICA_APP.. This seems like an unnessecearly complication which is not nessecerly since it would just lead to confusion among the pilots.


If you really wanted this to work then you would have to use a - between the ICAO and middle letters. Ex: LIRR-EW0_APP
The issue with this however is that it would not allow for relief logons at all.

I would highly recommend to reconsider the logons here, they just seem to make a understandable logon system become complicated for no gain at all.

**Comment by Adrian2k** [comment]
> @Adrian2k I have a question, on Milano Malpensa we will need the following changes: LIMM_W_APP becomes LIMM_ASW_APP LIMM_E_APP becomes LIMM_ADE_APP LIMM_N_APP becomes LIMM_ANE_APP LIMC_F_APP becomes LIMC_MAR_APP but my guess is that the following line will match both `LIMM_*_APP` and `LIMC_*_APP` is that correct? `LIMC|Milano-Malpensa|45.6299|8.723094|LIMM|LIMM|0`

Correct.

**Comment by mferraroni** [comment]
Rename will not be done, thus closing this PR.

**Pull request closed without merging**
