### PR TITLE
airspace change above LOWI part1

### PR DESCRIPTION
**Pull request by seelenkrieger**
corrected LOVV airspace above LOWI (LOVV is only responsible below FL165)

EDMM will send you the second change for this area above FL165

### CODE REVIEW

**Comment by seelenkrieger** [comment]
sorry seems I'm to stupid for this github, its the last 2 files (6f20eb3 and 205c8b9)

**Comment by Adrian2k** [comment]
Hi. You need to perform the changes with our files. If you download a copy of our files and do the changes in them, it should not revert all the other changes.

If your fork is very out of date, you can try to delete your fork (Settings >Delete this repository) and then fork this repository again.

**Review by Adrian2k — CHANGES_REQUESTED** [review]
Hi, there are over 30000 changes here. You need to perform the changes with our files. If you download a copy of our files and do the changes in them, it should not revert all the other changes.

If your fork is very out of date, you can try to delete your fork (Settings >Delete this repository) and then fork this repository again.

**Comment by seelenkrieger** [comment]
> Hi, there are over 30000 changes here. You need to perform the changes with our files. If you download a copy of our files and do the changes in them, it should not revert all the other changes.
> 
> If your fork is very out of date, you can try to delete your fork (Settings >Delete this repository) and then fork this repository again.

Sorry unfamilary with Github. I have updated now, so I must create a new pull request or ist it possible to enter it here in this pull?

**Comment by seelenkrieger** [comment]
see https://github.com/vatsimnetwork/vatspy-data-project/pull/311

**Pull request closed without merging**
