### PR TITLE
GeoJSON format

### PR DESCRIPTION
**Pull request by NelisV**
Initial draft of the GeoJSON format.

### CODE REVIEW

**Review by Adrian2k — APPROVED** [review]

**Comment by meltinglava** [comment]
So one thing. We do not need the extention flag in properties. We can apply extentions like at the bottom example on https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.9 . For Vatspy first one should be the main area, and the following boundaries are defined as extentions.

**Comment by meltinglava** [comment]
Also oceanic should be a boolean (true/false) instead of 0 or 1

**Comment by NelisV** [comment]
Still working on a new version, but converted oceanic to boolean. I checked regarding the label position, while allowed in json, no other gis standard allows nested values as properties.

**Comment by NelisV** [comment]
> as per the geojson spec it should be valid https://datatracker.ietf.org/doc/html/rfc7946#section-3.2

True, it is allowed in JSON and GeoJSON to add any json object, including arrays, no other geospatial standard allows it. So once you start using this geojson in something like QGIS, GDAL or Mapbox, only simple key value pairs are supported.

**Comment by dsolesvik** [comment]
Note: ZJSY still hasn't been fixed, I'll be making a new PR tomorrow, most likely, pushing the fix for that. But URRV has been fixed.

**Pull request closed without merging**
