### PR TITLE
Update Canada to reflect TCA Boundaries

### PR DESCRIPTION
**Pull request by kolbyd**
ref. https://github.com/vatsimnetwork/vatspy-data-project/pull/186

### CODE REVIEW

**Review by Adrian2k — APPROVED** [review]

**Review by Adrian2k — CHANGES_REQUESTED** [review]
image

Just noticed this, shouldnt CZQM cover this area if CZUL does not?

**Comment by kolbyd** [comment]
Good catch! It's been fixed :)

**Comment by prryplatypus** [comment]
smh Kolby

**Comment by NelisV** [comment]
I'd also suggest to reduce the point count of the arcs by about half, to keep in line with the other arcs in the dataset. it's quite a lot of points for a small piece of map 😅

**Comment by kolbyd** [comment]
Been updated to do half of the points in the arc.

As for @prryplatypus, I smh to you as well 😅

**Review by Adrian2k — APPROVED** [review]
I will approve it, @NelisV can double check if the borders still are correctly alligned.

**Comment by NelisV** [comment]
@kolbyd I don't see any difference compared to your older commit. Did you upload the correct file?

**Comment by NelisV** [comment]
Ah i see, you changed the resolution of one of the arcs, but not the other 3 in your edited sectors. Can you adjust the others aswell?

**Comment by kolbyd** [comment]
https://github.com/vatsimnetwork/vatspy-data-project/pull/187/commits/ac7618234ef80e2ddb3d76b3007fc2775d39af5b I’m fairly sure I did CZUL, CZQM and CZQX for that arc in this commit, maybe I’m missing something?

**Comment by NelisV** [comment]
Ah wait, i get it, we're talking past each other ;)
You reduced the pointcounts for all 3 FIR's bordering A, while the request is to do the same for B, C and D
image

**Review by NelisV — CHANGES_REQUESTED** [review]
Ah wait, i get it, we're talking past each other ;)
You reduced the pointcounts for all 3 FIR's bordering A, while the request is to do the same for B, C and D
image

**Comment by kolbyd** [comment]
I've updated C and D. I'm not going to touch B as that was not my change and has been in there for a long time :)

**Review by NelisV — APPROVED** [review]
Looks good, thanks for bearing with me :)

**Pull request merged**
