### PR TITLE
Add some airfields for Tyumen (USTV) and Yekaterinburg (USSV) FIRs

### PR DESCRIPTION
**Pull request by sanek1000804**
## Description of changes
This change will add airfields that exist and are not already added to the database

## Reason and motivation
This change will be useful for our FIRs because this airfields will be displayed correctly, when people fly from/to them

## Approved contributior

- [x] I am on the approved contributers list
- [ ] I have sent an request by email to get approved
- [ ] Someone on the approved contributer list will review this request

### CODE REVIEW

**Review by Adrian2k — APPROVED** [review]

**Review by NelisV — CHANGES_REQUESTED** [review]
Hey @sanek1000804 can you review this? It's based on the master branch, if we merge like this our request template and readme will be overwritten.

**Comment by Adrian2k** [comment]
It is fine to be merged.

**Comment by sanek1000804** [comment]
@NelisV @Adrian2k Do I still need to fix something or is the problem resolved?

**Comment by sanek1000804** [comment]
Anyway, I decided to make new PR #733. Review it, please.

**Review by NelisV — APPROVED** [review]

**Pull request merged**
