### PR TITLE
ULLL update

### PR DESCRIPTION
**Pull request by sanek1000804**
By Alexander Pervov
image

### CODE REVIEW

**Comment by sanek1000804** [comment]
This changes are actual for airac 2210

**Review by Adrian2k — CHANGES_REQUESTED** [review]
Airports which has the FIR's ULAA, ULKK, ULMM, ULWW, UUYY assosiated with them needs to be assigned a new FIR.

**Comment by sanek1000804** [comment]
> Airports which has the FIR's ULAA, ULKK, ULMM, ULWW, UUYY assosiated with them needs to be assigned a new FIR.

Oh yeah, now I have noticed that. Will correct.

**Comment by sanek1000804** [comment]
> Airports which has the FIR's ULAA, ULKK, ULMM, ULWW, UUYY assosiated with them needs to be assigned a new FIR.

Check it now, please

**Review by NelisV — CHANGES_REQUESTED** [review]
With our current policy it's not going to be possible to implement all these splits. Sectors can only be drawn in on the FIR level or if the amount of hours on the network permits it. Both are not the case after these changes. 

image

**Comment by sanek1000804** [comment]
> With our current policy it's not going to be possible to implement all these splits. Sectors can only be drawn in on the FIR level or if the amount of hours on the network permits it. Both are not the case after these changes.
> 
> image

I thought, it is possible to draw them because it the past it was different FIR's, so this boundaries are already existing now. And we just wanted to rename them correctly and make most of used ATC positions.

These changes are necessary because Control sectorization are regularly used in St. Petersburg, because they are, in fact, the former FIRs.

**Comment by sanek1000804** [comment]
Previous callsigns (such as ulaa, ulmm, ulww, etc.) are not used at all now. So I think it would be easier to replace them with actual sector callsigns. (old FIR merged into one FIR ULLL and became sectors in December 2021)

**Comment by Adrian2k** [comment]
First of all, the FIR's needs to be defined with a - instead of _.
For example ULLL-AM instead of ULLL_AM

Secondly, with the current proposed solution, the whole ULLL FIR will be shown as active regardless of what ULLL_CTR sector is online. ULLL_AM_CTR and ULLL_WK_CTR is going to both light up the whole ULLL FIR, this is a vatspy limitation.
The way to go around this is by changing your logins to ULLL-AM_CTR, ULLL-WK_CTR, and so on. This will make VATSpy show the sectors as you defined them. 
This solution however will need you to advise all your FIR neighbors of this change, otherwise they will no longer see you online in their sectorfiles.

**Comment by sanek1000804** [comment]
> First of all, the FIR's needs to be defined with a - instead of _. For example ULLL-AM instead of ULLL_AM
> 
> Secondly, with the current proposed solution, the whole ULLL FIR will be shown as active regardless of what ULLL_CTR sector is online. ULLL_AM_CTR and ULLL_WK_CTR is going to both light up the whole ULLL FIR, this is a vatspy limitation. The way to go around this is by changing your logins to ULLL-AM_CTR, ULLL-WK_CTR, and so on. This will make VATSpy show the sectors as you defined them. This solution however will need you to advise all your FIR neighbors of this change, otherwise they will no longer see you online in their sectorfiles.

Ok, I will discuss with ULLL leadership. 

Question about callsigns. I saw the callsigns with _ at EDDM. It turns out that they also do not work and show the entire zone, and not the one that is specified?

**Comment by Adrian2k** [comment]
What logons the different regions choose to use it upto them, however regions such as EDDM range over about 200-300nm.
Regardless of what EDMM sector is online, it will display the whole EDMM how it is now. However the sector indicators will guide pilots to where the controllers might controll. Also there excists other map plotting services such as map.vatsim.net that also uses this dataset that can display these splits accordintly.

The new ULLL FIR will range over 2000nm and from my understanding none of the ULLL sectors will actually cover the whole of ULLL.

With the current implementation, regardless of what ULLL sector is online, it will show the whole 2000nm+ sector, regardless of where they cover. It will be confusing for the pilots and likely result in pilots calling up the ATC when the ATC does not cover that area. Ultimately it is up to you how you want to do it, but the current proposal does not seem to make it more confusing for pilots than how it is today.

**Comment by sanek1000804** [comment]
> What logons the different regions choose to use it upto them, however regions such as EDDM range over about 200-300nm. Regardless of what EDMM sector is online, it will display the whole EDMM how it is now. However the sector indicators will guide pilots to where the controllers might controll. Also there excists other map plotting services such as map.vatsim.net that also uses this dataset that can display these splits accordintly.
> 
> The new ULLL FIR will range over 2000nm and from my understanding none of the ULLL sectors will actually cover the whole of ULLL.
> 
> With the current implementation, regardless of what ULLL sector is online, it will show the whole 2000nm+ sector, regardless of where they cover. It will be confusing for the pilots and likely result in pilots calling up the ATC when the ATC does not cover that area. Ultimately it is up to you how you want to do it, but the current proposal does not seem to make it more confusing for pilots than how it is today.

And is map.vatsim.net takes data not from this project?

**Comment by sanek1000804** [comment]
> The new ULLL FIR will range over 2000nm and from my understanding none of the ULLL sectors will actually cover the whole of ULLL.

ULLL_CTR sector is covering the whole ULLL

**Comment by sanek1000804** [comment]
I discussed this with the ULLL staff and they said they would change the callsigns if required. In that case, will you add all the changes?

**Comment by sanek1000804** [comment]
@Adrian2k @NelisV

**Pull request closed without merging**
