### PR TITLE
Addition of various Event Sectors

### PR DESCRIPTION
**Pull request by dirtyformal**
Kia Ora all,

Following changes have been made to airspace owned by VATNZ - 

- **Addition of NZAA-R_CTR - Auckland (Raglan)** -  This is a real-life sub-sector of Auckland Control, and has been defined as an Event Only position since our last major Sector shuffle. This sector is automatically covered by Auckland Control when -R is not online. I have also changed the ownership of aerodromes within NZAA-R's bounds.
- **Addition of NZAA-F_APP - Auckland Finals** - Event only position that controls aircraft on final approach below 5000 feet.
- **Addition of NZWN-F_APP - Wellington Finals** - Event only position that controls aircraft on final approach below 5000 feet, and all traffic to Woodbourne if that traffic is at 5000 feet or below.

This data has been tested by myself on the network, with all three positions looking good.

Any issues let me know.

### CODE REVIEW

**Comment by Adrian2k** [comment]
**First**: Do you actually login as NZAA-R_CTR, NZAA-F_APP and NZWN-F_APP, or do you use the same logons as the majority of VATSIM which would be NZAA_R_CTR, NZAA_F_APP and NZWN_F_APP?

**Second**: Regarding NZAA-R sector, we attempt to avoid VACC's adding all their different sector splits that are very rare to see online, it clutters the map and the more sectors that are added the more difficult it is to understand who controlls what. I would understand it so that NZAA_CTR is online at the same time as NZAA-R, and would therefore issue the correct handoff's regardless.

**Comment by dirtyformal** [comment]
We logon using the callsigns stated above - NZAA-R_CTR, NZAA-F_APP as these are subsectors of that unit.

We have some events coming up in the future that specifically utilize the Raglan sector, and it's independence in this display is a critical enabler.

**Comment by Adrian2k** [comment]
Sorry for the long wait. We have discussed the PR and as I stated above, we avoid adding splits that is rare to see online, especially event sectors. NZAA-R has only been online for 2 hours this year (compared to NZAA's 520 hour), and during an event, you will have ATC that tells you where to go.

We can accept the APP-specific entries as it does not clutter up the map more, but NZAA-R has been rejected by the team.

**Comment by dirtyformal** [comment]
That's incredibly disappointing. 

Would you like me to edit my PR?

**Comment by dirtyformal** [comment]
@Adrian2k - I have edited the PR to remove the Auckland (Raglan) Sector, as well as references to it. 

In doing this, I've also had a flick through all of the New Zealand Aerodromes, and updated them accordingly. In some cases, the ICAO has been reassigned, or the name of the aerodrome has changed.

Tested on my end, with everything passing.

**Review by NelisV — APPROVED** [review]

**Review by Adrian2k — APPROVED** [review]

**Pull request merged**
