### PR TITLE
Create install.bat

### PR DESCRIPTION
**Pull request by kusterjs**
simple, but might help a lot of people to place the files correctly. The folder from the zip needs to be extracted, then run the .bat file. All done.

### CODE REVIEW

**Comment by pedro2555** [comment]
#15 was rejected with a similar solution. Good luck. I still see a considerable amoints of downloads on the msi I provide.

**Comment by kusterjs** [comment]
@pedro2555 understandable, don't know why such initiatives are not accepted. Let's hope the best for the future.

**Comment by nepetadosmil** [comment]
Let us have a think about this one. I'm slightly more optimistic with this one since it's pretty straightforward and requires no sort of build 🤔

**Comment by pedro2555** [comment]
@nepetadosmil _the build process is 100% automated, requiring a `git push` as you do today._

Yet, major major improvement. Definitly not expecting you, or anyone else, to voice any sort of consideration. I was absolutly expecting my comment to be deleted, as others I'e posted have been in the past.

Keep improving, still a long way to go. Much luck, all the best.

**Comment by nepetadosmil** [comment]
I mean, if you want me to delete it... lol
Merging now.

**Comment by pedro2555** [comment]
@nepetadosmil that is your decision my friend. I'm a mere spectator at this point. And your looking bad from here.

**Comment by pedro2555** [comment]
I'm decomissioning the updates I provide in favpr of this solution.

**Pull request merged**
