### PR TITLE
VATPRC Update 2112

### PR DESCRIPTION
**Pull request by XCSWxcsw**
Update ZSCN/ZSAM ACC boundaries
Add/Remove some outdated airports

9SO8K{TW9CQ7)IZ)WQYBCVL

### CODE REVIEW

**Comment by XCSWxcsw** [comment]
@Adrian2k @NelisV Data of this branch is from 2110 should be update based on 2111

**Review by NelisV — CHANGES_REQUESTED** [review]
image
Could you have a look at the 3 points i've marked? They seem to misalign with the polygons already in the data. If approved this will be merged with 2112. 10 and 11 are already released.

**Comment by XCSWxcsw** [comment]
@NelisV Those 3 are from other sectors. Left above is from ZGHA others are ZSHA-AR22

**Comment by NelisV** [comment]
> @NelisV Those 3 are from other sectors. Left above is from ZGHA others are ZSHA-AR22. But I could connect them if you want to:)

Yes, please connect where they merge, want to prevent gaps between sectors. Thanks!

**Comment by XCSWxcsw** [comment]
> > @NelisV Those 3 are from other sectors. Left above is from ZGHA others are ZSHA-AR22. But I could connect them if you want to:)
> 
> Yes, please connect where they merge, want to prevent gaps between sectors. Thanks!

Done, Could you please check again? I will delete other irrelevant connection points to ensure that it is as concise as possible. But for next PR maybe

**Review by NelisV — APPROVED** [review]
Looking good! 

xiè xiè!

**Comment by XCSWxcsw** [comment]
> xiè xiè!
totally correct!! Haha!

image

btw, did that not update to 2112 branch?

**Comment by NelisV** [comment]
Ah yes, you're right. that still needs to be pushed onto the next month.

**Comment by NelisV** [comment]
@XCSWxcsw Hey Rudi, is this solved now vat-spy.dat is updated?

**Comment by XCSWxcsw** [comment]
> @XCSWxcsw Hey Rudi, is this solved now vat-spy.dat is updated?

Hey, you wanna me to solve this conflict?

**Comment by NelisV** [comment]
> 
> 
> > @XCSWxcsw Hey Rudi, is this solved now vat-spy.dat is updated?
> 
> Hey, you wanna me to solve this conflict?

If you can, that would be great.

**Comment by XCSWxcsw** [comment]
> > > @XCSWxcsw Hey Rudi, is this solved now vat-spy.dat is updated?
> > 
> > 
> > Hey, you wanna me to solve this conflict?
> 
> If you can, that would be great.

Ah. No worries. I thought you will do that. I will do that later😉

**Comment by XCSWxcsw** [comment]
@NelisV I'm not sure if I did the correct :( , show diff does not work, can you check?

**Comment by NelisV** [comment]
Oof, no something went wrong here. @Adrian2k could you help Rudi with his vatspy.dat?

**Comment by XCSWxcsw** [comment]
Is there anything that I need to do? XDXD @NelisV @Adrian2k

**Comment by Adrian2k** [comment]
Done.. 
@XCSWxcsw can you double check that all the changes you wanted in vatspy.dat is included now?

**Comment by XCSWxcsw** [comment]
@Adrian2k looks perfect! But hold on for merge, I need delete some outdated airport from VATSpy.dat

**Comment by XCSWxcsw** [comment]
Now done with all thing @Adrian2k Thanks for the help!

**Review by Adrian2k — APPROVED** [review]

**Pull request merged**
