### PR TITLE
VATPRC Update 2306

### PR DESCRIPTION
**Pull request by RudiZhang**
ZWTC name changed
add PEK_APP
add ZBPE ZSHA ZJSA split sector

### CODE REVIEW

**Comment by RudiZhang** [comment]
if merging to 2305 will be also fine

**Review by NelisV — CHANGES_REQUESTED** [review]
Hey Rudi. 

We have reviewed this and don't think the amount of hours on these sectors allow for them to be split on the map. There are already a lot of sectors in this area of the world and more clutter will confuse the average pilot even more. Consolidation here would be more useful instead of more splits. 

Best, 
Niels.

**Comment by RudiZhang** [comment]
> Hey Rudi.
> 
> We have reviewed this and don't think the amount of hours on these sectors allow for them to be split on the map. There are already a lot of sectors in this area of the world and more clutter will confuse the average pilot even more. Consolidation here would be more useful instead of more splits.
> 
> Best, Niels.

Hi Nelis,
What I need to emphasize is that these sectors are not event sectors, but regular daily sectors. These sectors have been included in our SOP, and any ATC may online for one of these sectors at any time. Maybe the current number of hours is not enough, because it is newly designated and intended to be kept for a long time. It is precisely because these enroute sectors are relatively unfamiliar to pilots that they need to be added to vatspy.

**Comment by NelisV** [comment]
Discussed via DM: Any top level sectors can be added. but the usage doesn't justify adding more sector splits at the moment. Let's review in a while and see if the situation changes.

**Comment by RudiZhang** [comment]
@NelisV He Nelis, now it should match the time requirement. Would you please check it again? Thanks!

**Comment by Adrian2k** [comment]
Checked the hours for this year:

ZBAA-N - 2 minutes
ZBAA-S - 6 minutes
ZBAA-W - Less than 1 minute
ZBAA-C - 6 minutes

ZJSY-L & O - Ok

ZSSS-N - Bit low but ok
ZSSS-S - Ok
ZSSS-W - 3:55hrs
ZSSS-C - Ok

I am leaning towards approving all but the ZBAA sectors, did I miss something with ZBAA? 
If I exclude ZBAA_CTR, all other logons only have a total of a bit over 2hrs.
(ZBAA_C1_CTR, ZBAA_C_CTR, ZBAA_N_CTR, ZBAA_S_CTR, ZBAA_T_CTR, ZBAA_W_CTR)

**Comment by RudiZhang** [comment]
@Adrian2k You can hold ZBAA's for now, that's for pre-release. Thanks :):)

**Review by Adrian2k — APPROVED** [review]
Approved due to planned VATspy changes

**Review by NelisV — CHANGES_REQUESTED** [review]
hey @RudiZhang yes, content is fine. however this needs to be refreshed so it doens't overwrite the changes made in previous airacs. Could you have a look?

**Pull request closed without merging**
