### PR TITLE
Merge UBBA-S geojson with UBBA

### PR DESCRIPTION
**Pull request by daniluk4000**
## Description of changes
Added UBBA-S sector to UBBA

image

## Reason and motivation
This matches this sector operation by local staff

## Approved contributior?

- [ ] I am on the approved contributers list
- [ ] I have sent an request by email to get approved
- [x] Someone on the approved contributer list will review this request

### CODE REVIEW

**Comment by Adrian2k** [comment]
Not sure if this is possible with our dataset - @NelisV will have to review it.

**Comment by daniluk4000** [comment]
> Not sure if this is possible with our dataset - @NelisV will have to review it.

Could it possibly be added as duplicate sector if this will become a problem? I mean same duplicate UBBA sector with different geometry, something like CZQM maybe?

**Comment by daniluk4000** [comment]
Also maybe my mistake was to move this too deep, since KZAK, PAZA and NFFF probably have something similar but on one more level than mine.

Anyway, I'll wait for review.

**Comment by NelisV** [comment]
hey @daniluk4000 in any case this'll need approval from someone on the contributors list. Can you ask them to reply here or send me an email verifying your status? @Atsamazz

**Comment by Jhenya5** [comment]
UBBA is approved

**Comment by ziplock1** [comment]
> hey @daniluk4000 in any case this'll need approval from someone on the contributors list. Can you ask them to reply here or send me an email verifying your status? @Atsamazz

@Atsamazz is no longer responsible for Caucasus region

**Review by ziplock1 — CHANGES_REQUESTED** [review]
You must change this one `[ 51.5, 42.0 ] ], [ [ 46.15, 38.85 ]` to `[ 51.5, 42.0 ] ] ], [ [ [ 46.15, 38.85 ] ` and then it's gonna work properly. Also I have a question why UBBA-S sector exists here, so maybe you shall delete it or add UBBA-E and UBBA-W.

**Comment by daniluk4000** [comment]
> You must change this one `[ 51.5, 42.0 ] ], [ [ 46.15, 38.85 ]` to `[ 51.5, 42.0 ] ] ], [ [ [ 46.15, 38.85 ] ` and then it's gonna work properly. Also I have a question why UBBA-S sector exists here, so maybe you shall delete it or add UBBA-E and UBBA-W.

That's a question for Georgy, and as I remember he confirmed that's how it should look like. Speaking of suggestion, I thought about the same in https://github.com/vatsimnetwork/vatspy-data-project/pull/802#issuecomment-2073633378, but I still wait for proper review by staff since it's still geojson and I don't see why this should break something

**Comment by ziplock1** [comment]
> > You must change this one `[ 51.5, 42.0 ] ], [ [ 46.15, 38.85 ]` to `[ 51.5, 42.0 ] ] ], [ [ [ 46.15, 38.85 ] ` and then it's gonna work properly. Also I have a question why UBBA-S sector exists here, so maybe you shall delete it or add UBBA-E and UBBA-W.
> 
> That's a question for Georgy, and as I remember he confirmed that's how it should look like. Speaking of suggestion, I thought about the same in [#802 (comment)](https://github.com/vatsimnetwork/vatspy-data-project/pull/802#issuecomment-2073633378), but I still wait for proper review by staff since it's still geojson and I don't see why this should break something (well maybe I don't know something ofc)

Just delete UBBA-S sector with notepad or something like that and then check your file with [geojson.io](url) , I think you'll understand what I'm talking about

**Comment by Hoverback** [comment]
> You must change this one `[ 51.5, 42.0 ] ], [ [ 46.15, 38.85 ]` to `[ 51.5, 42.0 ] ] ], [ [ [ 46.15, 38.85 ] ` and then it's gonna work properly. Also I have a question why UBBA-S sector exists here, so maybe you shall delete it or add UBBA-E and UBBA-W.

Because UBBA_E and UBBA_W are already existing individual parts of UBBA main airspace https://prnt.sc/9dUydT3Bj7zr

**Comment by Hoverback** [comment]
By the way, same separated type of the sector already exists. RU-NWS_FSS covers UMKK airspace, what is separeted of main. I think it makes sense to take an example from there.

**Review by ziplock1 — CHANGES_REQUESTED** [review]
You forgot to put a comma in the end of line

**Comment by daniluk4000** [comment]
> This still doesn't load in QGIS. Invalid GeoJSON. Please check and fix for the next release.

Yeah my apologies, I broke it with yesterdays fixes. Please re-checj

**Review by NelisV — APPROVED** [review]

**Review by ziplock1 — APPROVED** [review]
LGTM!

**Pull request merged**
