### PR TITLE
Splitting WBGG from WBFC

### PR DESCRIPTION
**Pull request by kusterjs**
WBFC splitted into smaller WBFC and new WBGG (covering western part)
Extension for WBFC (= dimensions of WBGG) added to light up again the entire FIR if only WBFC is online
resolving #96

### CODE REVIEW

**Review by NelisV — CHANGES_REQUESTED** [review]
This will require some more work, your new borders don't align in a lot of places. Please make sure the polygons meet in the same coordinates. 
image
image
image
The misalignments in my last image were already in the data before your edits. But if you could fix that too, would be nice :)

**Comment by kusterjs** [comment]
@NelisV Can't you just fix them when you already display them? I don't have such a tool and just took the existing borders. So at least it won't be worse.

**Comment by NelisV** [comment]
Yeah if i look a bit further, there are more borders in that region that'll need some work. I'll add it to my to:do list.

**Comment by kusterjs** [comment]
Don't know either of them, sorry.

**Comment by kusterjs** [comment]
@NelisV updated accordingly, please verify

**Review by NelisV — APPROVED** [review]
Allright, thanks!

**Review by Adrian2k — APPROVED** [review]

**Pull request merged**
