### PR TITLE
Significant VATRUS changes

### PR DESCRIPTION
**Pull request by Jhenya5**

### CODE REVIEW

**Comment by Adrian2k** [comment]
Hi @Jhenya5 

You will need to make the changes in the files available in the Github project. These files you have uploaded will overwrite many of the changes the other countries have done the last several months.

**Review by NelisV — CHANGES_REQUESTED** [review]
Hey @Jhenya5 this still needs to be looked at, you're changing too much. Did you base your PR on the latest release?

**Comment by Jhenya5** [comment]
Hi, Nelis, I didn't understand, what is meant by "Did you base your PR" ?
Can you please contact me via VATSIM Discord ?
862634, Evgeny, VATRUS Director

**Comment by Adrian2k** [comment]
> Hi, Nelis, I didn't understand, what is meant by "Did you base your PR" ?
> Can you please contact me via VATSIM Discord ?
> 862634, Evgeny, VATRUS Director

He means did do the changes in our dataset (downloaded from github), or did you just upload some VATSpy files you had from before?

**Comment by NelisV** [comment]
This can be closed, changes included in #313

**Pull request closed without merging**
