### PR TITLE
🔨 South Korea ACC & Airport Update (Ver 2)

### PR DESCRIPTION
**Pull request by PlAn-K**
✅ Update ACC Boundaries (Added RKDA-W, Coords Changed)
✅ Update South Korea Airports (ACC Changed)

### CODE REVIEW

**Review by NelisV — CHANGES_REQUESTED** [review]
The new splits looks good, but would be great if you could also fix some older gaps that were already in the data. In the image: the red lines to the north and south. 
image

**Comment by PlAn-K** [comment]
Sorry for delay, Files will be updated within  3 days.

**Comment by PlAn-K** [comment]
@NelisV Solved :)

**Review by NelisV — APPROVED** [review]
Looks good, thanks!

**Review by Adrian2k — APPROVED** [review]

**Pull request merged**
