### PR TITLE
Remove MYNN_CTR geometry (MYNN now uses KZMO)

### PR DESCRIPTION
**Pull request by erikquinn**
Following a new LOA, the previous MYNN_CTR airspace is no longer in use, and should be removed.

For confirmation, feel free to see the relevant letter of agreement here, which became effective on the first of June:

https://nassau.vatcar.net/wp-content/uploads/2022/04/VATCAR-ZMA_LOA_v1.5.pdf 

image

### CODE REVIEW

**Review by Adrian2k — CHANGES_REQUESTED** [review]
All the airports which has MYNN as their FIR needs to be changed too.

**Comment by erikquinn** [comment]
@Adrian2k Ah, yes, sorry-- should have called that out in the PR description.

The airports (and associated approach controls) do still belong to the Nassau FIR, and not to Miami. So I thought maybe that meant the airports should remain marked as under MYNN? Or should they be assigned to ZMO, because that is the center that provides the top-down coverage?

Just want to confirm before making the change.

**Comment by Adrian2k** [comment]
If the FIR is not defined, then airports should not have that undefined FIR defined.

**Comment by erikquinn** [comment]
Got it 👍

**Comment by Jeeveegee** [comment]
All looking good on behalf of VATCAR / Nassau.

**Review by NelisV — APPROVED** [review]
correct for the geojson end

**Review by Adrian2k — APPROVED** [review]

**Pull request merged**
