### PR TITLE
Update to LPPO-TMA Definition

### PR DESCRIPTION
**Pull request by rffuret**
## Description of changes
Creation of accurate lateral limites for the AoR of "LPPO-TMA", controlled by LPPO_CTR

## Reason and motivation
Correct pilot awareness of lateral limits, especially due to the direct interface with LPPC Madeira Sector

## Approved contributior?

- [x] I am on the approved contributers list
- [ ] I have sent an request by email to get approved
- [ ] Someone on the approved contributer list will review this request

### CODE REVIEW

**Comment by NelisV** [comment]
Hey @rffuret you're not on the approved contributors list, please follow the procedure to get verified or make sure @becas22 leaves a review here.

**Comment by becas22** [comment]
I approve this too

**Review by NelisV — APPROVED** [review]

**Comment by NelisV** [comment]
@rffuret this seems to result in a merge conflict. Is the LPPO update not covered by the other PR?

**Comment by rffuret** [comment]
Hoi @NelisV 
No, this should have been a clean fork with changes only to LPPO

**Comment by NelisV** [comment]
> Hoi @NelisV No, this should have been a clean fork with changes only to LPPO What is conflicting?

image

**Comment by rffuret** [comment]
That is weird. Could you kindly revert that one and then I'll check for the next airac what the impact is and why it doesn't work?

**Pull request merged**
