### PR TITLE
Corrected invalid FIR designators 2

### PR DESCRIPTION
**Pull request by ChrisXPP**
More airports to be fixed... 
Also refers to #232 .

### CODE REVIEW

**Comment by NelisV** [comment]
@ChrisXPP could you merge this with #433?

**Comment by ChrisXPP** [comment]
@NelisV I would like to merge both #444 and #443, but have no idea how to...

**Comment by NelisV** [comment]
Go here: https://github.com/ChrisXPP/vatspy-data-project/tree/patch-5 and upload a new vatspy.dat that has all the changes

**Comment by ChrisXPP** [comment]
Uploaded a revised vatspy.dat file to PR #443 . Closing this one.

**Pull request closed without merging**
