### PR TITLE
LSAS sectors update

### PR DESCRIPTION
**Pull request by kusterjs**

### CODE REVIEW

**Comment by Adrian2k** [comment]
Does this PR replace #502?

**Comment by kusterjs** [comment]
> Does this PR replace #502?

negative. It's a fine tuning on top of it.

**Comment by Adrian2k** [comment]
We can not merge both, it would result in conflicts.

Does #502 have any entries that this PR does not? If not then this is a replacement of it.

**Comment by kusterjs** [comment]
yes, there is one additional commit in #506. I see the other commits from @Alcabohni are part of it as well. So actually it should work if you only merge #506 (it is #502 + 1 additional commit).

**Review by NelisV — CHANGES_REQUESTED** [review]
image
So there are some area's that need to be looked at, in the area's i have marked the borders don't align. Could this be checked/adjusted?

**Comment by kusterjs** [comment]
@Alcabohni

**Comment by Alcabohni** [comment]
> So there are some area's that need to be looked at, in the area's i have marked the borders don't align. Could this be checked/adjusted?

@NelisV What Langen Sectors are not correlating with Borders? i cant find non matching between LSAS/LSAZ and EDGG/EDGG-B/EDGG-K in my Commits

**Comment by NelisV** [comment]
image
So on the line between LSAG and LSAZ

image
Similar missing points on the line between EDGG and LSAS 

image
And a gap between LSAS and LIMM

**Comment by Alcabohni** [comment]
Yeah LSAG/LSAZ i had found, and allready corrected, but as this PR is from Jonas, i have do a PR to his repo so that he can add in this one i think.

LIMM ive found as well the two missing Points, Langen i will do after Dinner. What Tool you use for the Comparsion of the Points/Borders?

**Comment by NelisV** [comment]
I use QGIS for this, i've made a document explaining the process. Bit outdated, but it still covers how to edit GeoJSON correctly.
https://github.com/NelisV/vatspy-geojson/wiki/Editing-Sector-Files-for-VAT-Spy

**Comment by kusterjs** [comment]
@NelisV I've integrated the corrections prepared by @Alcabohni in this pull request.

**Review by NelisV — APPROVED** [review]
Thanks for the fixes, all good now.

**Review by Adrian2k — APPROVED** [review]

**Pull request merged**
