### PR TITLE
GMMO

### PR DESCRIPTION
**Pull request by kusterjs**
implementing #219

### CODE REVIEW

**Review by NelisV — CHANGES_REQUESTED** [review]
This PR splits the GMMM FIR in half. Don't think that's intended looking at #219 . Before GMMM would cover the entire FIR, and GMMO would shelf over the western part. Please verify this change with local staff so we can be sure what it should be.

**Comment by kusterjs** [comment]
The split was already present, however only covering half of the GMMO sectors. Added an extension definition to have the GMMO part also covered by GMMM, which is done according GNG data.

**Comment by Adrian2k** [comment]
image
GMMM covers the area when GMMO is offline.

**Comment by kusterjs** [comment]
Exactly, which is why I added the extension. So it will show GMMM correctly, but also GMMO, if online.

**Review by NelisV — APPROVED** [review]

**Review by Adrian2k — APPROVED** [review]

**Pull request merged**
