### PR TITLE
VATPRC Update 2206

### PR DESCRIPTION
**Pull request by RudiZhang**
huge airspace change

change of VHHK is approved by HK vACC @EightSmart

### CODE REVIEW

**Comment by EightSmart** [comment]
Approved by ACCHKG5

**Review by EightSmart — APPROVED** [review]

**Review by NelisV — APPROVED** [review]
the geojson looks good 👌🏻 
image

**Comment by RudiZhang** [comment]
@NelisV I think you're using the wrong file. it should be 
image

**Comment by NelisV** [comment]
> @NelisV I think you're using the wrong file. it should be image

My image only contained the geometry which was changed in this update. In full it looks just like yours ;)

**Review by Adrian2k — APPROVED** [review]

**Comment by RudiZhang** [comment]
> > @NelisV I think you're using the wrong file. it should be image
> 
> My image only contained the geometry which was changed in this update. In full it looks just like yours ;)

ah ic hahaha

**Pull request merged**
