### PR TITLE
Update Moroccan Oceanic Sector Name

### PR DESCRIPTION
**Pull request by LocatedAir**
- Changed the Moroccan Oceanic Sector from GMMO to GMAC as we no longer refer it to GMMO in the Morocco vACC. GMAC Is the correct name.

### CODE REVIEW

**Comment by Adrian2k** [comment]
You need to change it in VATSpy.dat aswell 

https://github.com/vatsimnetwork/vatspy-data-project/blob/852be00fc4f2ee9efd91b02a697ffe146ab75f82/VATSpy.dat#L17957

**Review by Adrian2k — CHANGES_REQUESTED** [review]
As above

**Comment by LocatedAir** [comment]
Should be fixed now, my sincere apologies. Thank you!

**Review by LocatedAir — COMMENTED** [review]
- replying to review to confirm change

**Review by NelisV — APPROVED** [review]

**Review by Adrian2k — APPROVED** [review]

**Pull request merged**
