### PR TITLE
Updated FIR Atlantico (SBAO), Amazonica (SBAZ) and Recife (SBRE) boundaries with its sectors

### PR DESCRIPTION
**Pull request by fonfs**
## Description of changes
Updates FIR Atlantico (SBAO), FIR Amazonica (SBAZ) and FIR Recife (SBRE) lateral limit and define its official sectorisation.

## Reason and motivation
SBAO lateral limit was updated in northern sector (expanded inside FIR SBAZ), SBAZ lateral limit was updated in northern sector (reduced in lieu of SBAO) and SBRE lateral limit was updated in eastern sector (expanded inside FIR SBAO).
Also, Vatsim Brasil has defined standard sectorisation, to be shown specifically when such position is online.

image

image

image

## Approved contributor?

- [X] I am on the approved contributers list
- [ ] I have sent an request by email to get approved
- [ ] Someone on the approved contributer list will review this request

I've been approved by Marcelo Barretto, Vatbrz Division Director.

### CODE REVIEW

**Review by NelisV — CHANGES_REQUESTED** [review]
Hi! We cannot merge like this as it creates misalignment with the bordering FIR's. This needs to be reworked. 
image
image
image

**Comment by fonfs** [comment]
@NelisV regarding internal borders, we can carry on with the new data, since we're already reworking the sectors to be aligned with RL. Regarding international borders, our data is the correct, since it follows the actual international boundary with other countries. The option we have is to intervene in these other FIRs (Cayenne, Paramaribo, Georgetown, Maiquetía, Bogotá, Lima, La Paz and, in the future, Asunción, Resistencia and Montevideo) to make them follow the correct boundary data.

Please, give us a feedback in this regard.

**Comment by NelisV** [comment]
@fonfs Hi, as long as your region agrees with it, i'm fine with you amending the international border to make them more precise.

**Comment by Adrian2k** [comment]
Feel free to submit a new PR when the issues above is resolved.
Closing this due inactivity

**Pull request closed without merging**
