### PR TITLE
VATWA AIRAC 2112 Update

### PR DESCRIPTION
**Pull request by VATWAOps**
West Asia Division has been doing a complete overhaul of its airspace after many years of being out of date. Changes are updates to the OAKX (Afghanistan), (OPKR) Karachi and (OPLR) Lahore FIRs.

VATSPY.dat
- Added Primary ACCs ( C,E,S,W) within OPKR FIR
- Added Primary ACCs (E,ISB,S,W) within OPLR FIR
- Added Primary ACCs (HE,HW,N,S) within OAKX FIR
- Changed name description for OAKX
- Changed name description for OPKR
- Changed name description for OPLR
- Added Control to Pakistan under Countries Section

GeoJSON Boundaries
- Added OAKX-HE/HWACCs (Note OAKX-N covers same airspace as OAKX-HE same with OAKX-S to OAKX-HW so didn't bother to add an additional sector to cover same area.)
- Added OPKR-C/E/S/W ACCs
- Added OPLR-E/ISB/S/W ACCs
- Re-defined OAKX FIR to counter-clockwise direction
- Re-defined OPKR FIR to counter-clockwise direction and amended FIR boundary line between OPLR
- Re-defined OPLR FIR to counter-clockwise direction and amended FIR boundary line between OPKR
- Amended VIDF FIR to match changes to OPLR FIR and its ACCS
- Amended VABF & VABX FIR to match changes to OPKR FIR and its ACCs

- Amended OIIX  & TEH-5E by adding an additional point to avoid non-alignment between OPKR & OPKR-S See picture below 
image

Amendments to VABF, VIDF, VABX FIRs are just temporary to avoid non-alignments with OPKR & OPLR FIRs. Expect full overhaul for these FIRs and the rest of India over the next couple airac cycles.

Any questions feel free to ask.

Regards

### CODE REVIEW

**Comment by NelisV** [comment]
This has some issues, I'm unable to open your GeoJSON in QGIS, Github also does not seem able to render your file. 
Furthermore, are these sector splits controlled consistently outside of events? As described in the readme, the general rule is that we only add whole FIR's to the dataset at the moment. 

Br.

**Comment by VATWAOps** [comment]
Hi.

I'll see what the issue is with the GEOJSON File. 

Ive seen the readme but i dont see any issue as the positions we have aren't classed as Events. All En-route positions within our division are primary positions that cover certain sections within the FIR.

Ill take a look now and revert back with the geojson file.

**Comment by NelisV** [comment]
The condition is not that they are classed as non-event sectors. The condition is that they are used regularly outside of events. If you look at the hours since 1-1-2021 you can see these positions are not controlled regularly and therefor i can't make an exception as per our policy. 

image
image
image

**Comment by VATWAOps** [comment]
Hi

I just don't see how a rejection is quiet justified. The general ruling you now class as a policy when really isn't a policy is somewhat bias if a request is somewhat similar to other request but gets rejected based on low activity. But other sectors get approved on similar bases is somewhat a bit bias if you ask me.

This is our splits for OAKX OKPR OPLR FIR
image
image

The ATC Hours are low fair enough but we've recently just approved the splits so any statistics regarding the splits before 12th November is irrelevant

Anyways if a rejection is what's offered fair enough but we will continue to work on the overhaul of our airspace and our sectors will start to not shown on VATSPY.

**Comment by raihan777** [comment]
Hi Nelis,
VATWA operations team working extensively on the revised sectors for Pakistan as Brodie has explained, please include the updated sectors in the next VAT-Spy update as the pilots flying in area cant see the new FIR boundaries after Lahore and Karachi are revised, Islamabad is added, Karachi and Lahore further divided in sub sectors, bandbox OPKR_CTR and OPLR_CTR are kept for low volume traffic though not recommended at all for high volume event traffic as we have experienced high traffic volume passed through both FIRs in 2 of recent events, **Silk Road to the Sky** and **World Flight 2021**  During such high volume traffic event, we will only open the sub sectors as defined though traffic will not have idea about the active sectors if not added to VAT-Spy update.  I hope the submitted update by Brodie gets approved, including OAKX split as well.  Thanks.

Raihan, VATWA1

**Comment by Adrian2k** [comment]
Just to clarify: We are denying neither OPKR_CTR nor OPLR_CTR, we are talking about all the subsectors within these two FIR's.

> But other sectors get approved on similar bases is somewhat a bit bias if you ask me.

You are not really coming with any examples here, it is a rule that was introduced this year. This was done as a result of FIR's adding every possible split into VATSpy, cluttering up the data and not being much helpful for either us or the pilots. I could come with examples here, but I think we both understand which regions we are talking about.

> please include the updated sectors in the next VAT-Spy update as the pilots flying in area cant see the new FIR boundaries after Lahore and Karachi are revised, Islamabad is added,

They will be able to see your main FIR's. 

> high volume event traffic as we have experienced high traffic volume passed through both FIRs in 2 of recent events, Silk Road to the Sky and World Flight 2021

Adding all the possible splits because they are staffed during events such as Silk Road to the Sky and World Flight 2021 as you mentioned are good examples of them being "event sectors" (event sectors as in primarely used only during events, not that they are only reserved for events).


Adding sector splits makes sense in regions such as the UK or Germany where only sub-sectors (such as LON_S_CTR or EDWW_A_CTR) are the normal way of operatoin. In regions such as the Netherlands, Denmark, Norway, Switzerland where staffing the whole FIR is the normal way of operation does not get these splits. Even if these sectors are splitted, we very often have neighbouring sectors issuing correct handoff's, and the sectors are displayed online regardless, as they have the same ICAO code as the main FIR. (Ex: ENOS_CTR and ENOS_N_CTR both displays ENOS FIR)


So right now we are only gonna approve the "main" FIR's, not the subsectors. If the sectors gets staffed enough then we can include them, but excluding them does not prevent you of being displayed on VATSpy.

**Comment by VATWAOps** [comment]
> You are not really coming with any examples here, it is a rule that was introduced this year. This was done as a result of FIR's adding every possible split into VATSpy, cluttering up the data and not being much helpful for either us or the pilots. I could come with examples here, but I think we both understand which regions we are talking about.

Please see the statistics examples I've provided

Lanarca - LCCC FIR
LCCC

Melbourne - YMMM FIR
ML

Tehran - OIIX FIR
OIIX

Ujung Pandang - WAAF FIR
WAAF

The difference between our and the ones i mentioned above as an example is our splits are brand new denying based on low ATC activity is baseless if they didn't exist prior to this month and basing statistics over a years period which i have already mentioned. Hence why i think its somewhat bias, and base denial towards atc activity then i thinks its time to have a really hard look on all the splits already approved. Especially recent ones approved like 

Canarias Oceanic - GCCO (Visit #420 )
image

Riyadh - OERD (Visit #422)
OERD

Both new to the vatspy family both approved low atc activity i would assume both recently new as well 

Also to add on and i will share the screenshot again our splits don't clutter the map there's no overlays between other splits the only overlay is the bandbox positions so mentioning that we don't add them to avoid clustering up the map is an understatement

image

Our splits are designed the same way as VATPAC and VATNZs there's no cluster no overlapping each sector (expect for the combined sector) represents its own mini ACC/FIR

> Adding sector splits makes sense in regions such as the UK or Germany where only sub-sectors (such as LON_S_CTR or EDWW_A_CTR) are the normal way of operation. In regions such as the Netherlands, Denmark, Norway, Switzerland where staffing the whole FIR is the normal way of operation does not get these splits. Even if these sectors are spilt, we very often have neighbouring sectors issuing correct handoff's, and the sectors are displayed online regardless, as they have the same ICAO code as the main FIR. (Ex: ENOS_CTR and ENOS_N_CTR both displays ENOS FIR)

Our split system that we use is the same as VATNZ and VATPAC uses. Our splits are either classed A. Multiple ACCs within an FIR that has its own unique ICAO codes like you see with Australia (You'll see more of an idea once India gets its update but here's an example image)

image

B. Multiple splits within the ACC within a FIR like OPKR, OPLR, OAKX. The difference is most places you describe use the underscore to it makes sense not to bother as you have mentioned but our positions defined by our operations department and division use the dash eg. OPKR-E_CTR and not OPKR_E_CTR.

image

This is what vatspy looks like with the changes we've requested.
vacc

All Splits you see here below use the underscore the only difference that happens behind the scenes is OPLR-ISB uses its own unique code of ISB_CTR instead of OPLR-ISB_CTR A full list of our enroute positions within OAKX, OPKR, OPLR are as follows.

OPKR_CTR, OPKR-E_CTR, OPKR-C_CTR, OPKR-S_CTR, OPKR-W_CTR
OPLR_CTR, OPLR-E_CTR, ISB_CTR, OPLR-S_CTR, OPLR-W_CTR
OAKX_CTR, OAKX-HE_CTR, OAKX-HW_CTR, OAKX-N_CTR, OAKX-S_CTR

> So right now we are only gonna approve the "main" FIR's, not the subsectors. If the sectors gets staffed enough then we can include them, but excluding them does not prevent you of being displayed on VATSpy.

Because we use the dash instead of the underscore probably 40-50% of our sectors wont show as online but rather unknown under the controllers list.

I am hoping this may reconsider the grounds of our request because without it an approval its going to make things a lot harder not just for controllers who are online but don't show as online but also for the pilots who fly but don't see us online.

**Comment by Adrian2k** [comment]
All the examples you provided other than Australia are from before the rule was implemented. We do not have the capability or local knownledge to change data from before this rule implementation. Their changes has therefore been "grandfathered" in, but if they make changes in the future they will be under the same restrictions. 

Australia just started using their sectors 2 months ago and have an very different way of doing their sectorisation, which with their current format can not be implemented into VATSpy otherwise. It should be mentioned that from my observation they do staff many differents sectors and not the same few ones.

**Comment by Adrian2k** [comment]
>Because we use the dash instead of the underscore probably 40-50% of our sectors wont show as online but rather unknown under the controllers list.

I suggest not using the dash in this case.

**Comment by Adrian2k** [comment]
OPKR|Karachi|OPKR-E|OPKR
OPKR|Karachi|OPKR-S|OPKR

These lines will allow it to be displayed, then we can check back in a few months if the subsectors really are needed. It is a quick and easy implementation if it meets our requirements. 

image

**Comment by Adrian2k** [comment]
Missed GCCO and OERD.

These are while you might disagree a bit different that your subsectors.
1. They are quite abit larger but also 2. Are their own "FIR's" if that makes sence. Not sure how to describe it.

If I am not mistaken, Saudi Arabia is also a region that previously has been rejected to have subsectors. OERD is not quite a subsector, also it is also just one additional FIR, not multiple.

**Comment by NelisV** [comment]
This will be moved to 2113.

**Comment by NelisV** [comment]
This will be closed shortly if there is no reply.

**Pull request closed without merging**
