### PR TITLE
Remove Outdated UK Military Definitions

### PR DESCRIPTION
**Pull request by jackedwards815**
The following are no longer used by VATSIM UK, EGVV covers Scottish and London FIRs for these functions (already depcited as such).

~~EGVV|Swanwick Military|LMLL|EGVV
EGVV|Swanwick Military|SWML|EGVV
EGVV|Swanwick Military|SWMIL|EGVV
EGVV|Swanwick Military|SWAN|EGVV
EGUJ|Neatishead Air Defence|NEAT|EGTT
EGQN|Buchan Air Defence|BUCH|EGPX
EGQN|Buchan Air Defence|BUAD|EGPX
EGQQ|Swanwick Military (North)|SMIL|EGQQ
EGOM|Spadeadam Range|SPAD|EGTT~~

and EGQQ FIR definition not required.

### CODE REVIEW

**Comment by Adrian2k** [comment]
@hsugden can you approve this?

**Comment by jackedwards815** [comment]
I am the VATSIM UK Ops Dir. btw. Here is the reference: https://github.com/VATSIM-UK/UK-Sector-File/pull/3004

**Comment by Adrian2k** [comment]
Ah, Harry is the only one on our approved list. Have you sent an email to Nestor as described on the project page so your account can be approved?

**Comment by jackedwards815** [comment]
I haven't no, I'll go and look at that 👍

**Review by Adrian2k — APPROVED** [review]

**Review by hsugden — APPROVED** [review]

**Review by NelisV — APPROVED** [review]

**Pull request merged**
