### PR TITLE
VATSIM Spain sectors update

### PR DESCRIPTION
**Pull request by ImAlex28**
## Description of changes

This pull request add new sectors and modify the current ones for VATSIM Spain.

## Reason and motivation

This pull request aims to update the sectorization of Spain to reflect our current sectorization and avoid confusion among pilots.
sectores-peninsula
sectores-insulares

## Approved contributior?

- [x] I am on the approved contributers list
- [ ] I have sent an request by email to get approved
- [ ] Someone on the approved contributer list will review this request

### CODE REVIEW

**Comment by Adrian2k** [comment]
Please rebase this PR - also in conflict atm

**Comment by ImAlex28** [comment]
Should be OK now

**Comment by Adrian2k** [comment]
Hello - sorry for the late review of this.
Usually it is not me who do the review of the geosjon files, but I will try my best.

Looks good - but question regarding this one:
image

What does this cover - or whats the purpose of this airspace? Is it limited by altitude or does it cover GND-UNL?

Reason for asking is as currently Spain + Casablanca airspaces are overlapping.

**Comment by ImAlex28** [comment]
Hi @Adrian2k , reason for the "overlapping" is that Spain has an Spanish Airport (GEML) in that territory. This sector provides ATS services to that airport. The coverage is SFC/6000ft. So in that sector Casablanca covers 6000ft/UNL.

Real reference for that sector: 
image

**Review by Adrian2k — APPROVED** [review]

**Pull request merged**
