### PR TITLE
Added FASA_CTR

### PR DESCRIPTION
**Pull request by dswoodward**
Added FASA_CTR - FACA and FAJA bandbox - introduced AIRAC2108

### CODE REVIEW

**Review by Adrian2k — APPROVED** [review]

**Comment by Adrian2k** [comment]
I have approved it, but if this are one sector that covers both FACA and FAJA top-down, then it is better to create a FIR that covers these 2 area's. Otherwise it will look like FASA only covers above FL245.

**Comment by dsolesvik** [comment]
@dswoodward Let me know if you would like me to do that for you.

**Comment by dswoodward** [comment]
This would be excellent if you could. I appreciate your help. Thank you.

**Review by NelisV — CHANGES_REQUESTED** [review]
Sounds like a plan, please add the changes to the firboundaries.dat 👌🏻

**Comment by dsolesvik** [comment]
#387

**Pull request closed without merging**
