### PR TITLE
Peterburg rework + R-sectors

### PR DESCRIPTION
**Pull request by daniluk4000**
## Description of changes

1. Changes formatting of Peterburg sector names
2. Adds R-sectors to ULLL
3. Take note that SW-sector currently contains two polygons

image

## Reason and motivation

R-sectors are taken from https://ulll.vatmap.ru by local staff request

## Approved contributior?

- [ ] I am on the approved contributers list
- [ ] I have sent an request by email to get approved
- [x] Someone on the approved contributer list will review this request

### CODE REVIEW

**Review by Jhenya5 — APPROVED** [review]
I hereby confirm these changes

**Review by NelisV — CHANGES_REQUESTED** [review]
As discussed, the borders need to be discussed and aligned before we can merge.

**Comment by daniluk4000** [comment]
Sectors have been fully reworked to align them with Euroscope data as well

image

image

**Review by NelisV — APPROVED** [review]
Very nice work! Looking great.

**Pull request merged**
