### PR TITLE
Added GCCO

### PR DESCRIPTION
**Pull request by dsolesvik**
Added GCCO Oceanic - GCCC Oceanic split, and also fixed small boundary issue with LPPO.
image
image
image

### CODE REVIEW

**Comment by dsolesvik** [comment]
> Just looking at the sectors for GCCC in GNG, and this presents GCCO as the following:
> image
> 
> (Difference being the corner just to the bottom left of the "GCCC" text on VATSpy.
> 
> Can you confirm that your version is intentionally made different to this? I couldn't find any level difference either.

Yes, you are right. Sorry, I didn't notice this when making my points. I'll update the PR with annother commit today.

**Comment by dsolesvik** [comment]
Converted to draft, will close and make a new PR  for this and #414 when both are approved.

**Comment by dsolesvik** [comment]
image
Fixed

**Comment by becas22** [comment]
I approve this

**Comment by dsolesvik** [comment]
Regarding vACC approvals: I already emailed Nestor to get approved, I am on the VATSPA staff list and have been approved by the vACC director. The changes have also been approved by the vACC and operations director.

**Comment by Adrian2k** [comment]
> Regarding vACC approvals: I already emailed Nestor to get approved, I am on the VATSPA staff list and have been approved by the vACC director. The changes have also been approved by the vACC and operations director.

You can just merge them into one PR if you are unable to keep them as two seperate. The Portugal one has already been approved by staff. Will then merge once all is OK.

**Comment by dsolesvik** [comment]
#420

**Pull request closed without merging**
