### PR TITLE
Added NFFN_CTR, updated airports

### PR DESCRIPTION
**Pull request by vatpacais**
Updated Airports that reside in NFFN_CTR boundary
Updated Vatpac airports from YMMM and YBBB to correct FIR
Removed tower callsigns from non towered VATPAC airports
Removed duplicate airports

### CODE REVIEW

**Review by prryplatypus — COMMENTED** [review]
Why is there so many airport/airport aliases being removed in this PR and what is the reason for each of the airport changes? I can understand all those switching from NFFF to NFFN, but what's up with all the others?

**Comment by vatpacais** [comment]
Basically I was doing a clean up.
The AY and AG airports are non controlled airports in VATPAC airspace. Even if they became controlled airports they do not require an alias as our standard for non Australian airports is to use the ICAO as the callsign prefix

There were some Australian airports shown as part of YBBB and YMMM, these were updated the the correct enroute sector

**Review by prryplatypus — CHANGES_REQUESTED** [review]
I'm concerned about the deletions for airports starting with `C`, `V`, `W`, `E`, etc... what's that all about?

**Comment by vatpacais** [comment]
They are all exact duplicates. I was just trying to help clean up the data. If its an issue feel free to keep them in the data

**Comment by vatpacais** [comment]
On checking, this line needs to be added back in to the file
KVLY|Harlingen Rio Grande Valley Intl TX|26.228506|-97.654394|VLY|KZHU|1

**Comment by vatpacais** [comment]
Closed and will resubmit with KVLY|Harlingen Rio Grande Valley Intl TX|26.228506|-97.654394|VLY|KZHU|1 added back in

**Pull request closed without merging**
