### PR TITLE
Update of Turkish airport coordinates

### PR DESCRIPTION
**Pull request by GTheill**
Revised LTXX airport coordinates. Approved by ACCTR6 gurselalp@trvacc.net

### CODE REVIEW

**Review by Adrian2k — CHANGES_REQUESTED** [review]
Please reduce the amount of decimals to maximum 6.

I checked a couple of the coordinates and they are still pretty much in the same area. Highly doubt you even need to update all these.

**Comment by GTheill** [comment]
Thank you for the comment Adrian.

Iust adjusted decimals as required. Some of the airports miss the aircrafts on the ground, especially on the eastern parts of Turkey. Vatspy shows those aircrafts floating on the map instead of landed. Also added newly introduced Rize-Artvin airport to the file. Main adjustment was to match all airport coordinates with the euroscope sectorfile.

**Comment by Adrian2k** [comment]
Thanks.

I now also see there is a space after the | divider on the coordinates.
This needs to be removed

**Review by NelisV — APPROVED** [review]
pre-approval, pending @Adrian2k s review.

**Review by Adrian2k — APPROVED** [review]

**Pull request merged**
