### PR TITLE
EFIN-J and EFIN-H sectors 

### PR DESCRIPTION
**Pull request by nakoale**
made according to Scandinavia vacc site for Finland

### CODE REVIEW

**Comment by nakoale** [comment]
Screenshot_10
Apparently i didnt make all these small sectors. J and H will be really useful for the fly and see santa event on 12nd/12

**Comment by nakoale** [comment]
Screenshot_9

**Comment by Adrian2k** [comment]
Are you a staff member of VATSIM Scandinavia?
Why does this PR also make changes to LCCC?

As described on the readme, accounts need to be verified now, so if you are a staff member please send an email as described in the readme to get your account verified.

**Comment by nakoale** [comment]
aa ok thought we could contribute to other vaccs even if we are not staff members

**Comment by Adrian2k** [comment]
Awaiting review from Helsinki staff..

**Comment by Adrian2k** [comment]
Denied by ACCSCA6 (Director of Helsinki FIR).

**Pull request closed without merging**
