### PR TITLE
KZAU KZMP KZOB Boundary Change

### PR DESCRIPTION
**Pull request by BeaconSlash**
Existing data for the northern portion of the KZAU airspace boundary is erroneous in multiple respects.

This data corrects the boundary to match real coordinates.  KZMP and KZOB boundaries were modified accordingly to conform with the change.  I have attached pictures with the various commits, derived from the GitHub map of this project, to directly illustrate the changes being made.

I sent emails yesterday to vatspy-data-project@vatsim.net in an effort to validate my account per the Readme.  I have not yet received a reply but wanted to have the data ready to go in a PR for whenever the team is willing/able.  My hope is this data would be incorporated in the 27 JAN 2022 chart date change.  I respectfully request this data not be outright rejected or ignored.

As a follow-up question, what was the raw source data for these boundaries?  It seems quite old.

Thank you for your assistance, and I hope to see these changes incorporated as soon as practicable.

### CODE REVIEW

**Comment by BeaconSlash** [comment]
Here is the per-commit boundary change progression:

KZAU Boundary Change to conform with actual boundary:
ZAU Change

KZMP Boundary Change to conform to KZAU boundary change:
ZMP Change

Illustration of KZOB change to conform to KZAU and KZMP boundary changes:
ZOB Change

Final depiction of KZAU KZMP KZOB boundary change:
Final Change

**Review by NelisV — CHANGES_REQUESTED** [review]
Looks good! Thanks for your contribution. This does however need to be merged into the 2201 branch instead of master and that seems to cause a few conflicts. Can you check that?

**Comment by BeaconSlash** [comment]
I can try. I'm not terribly experienced with GitHub, but I'll try.

**Comment by BeaconSlash** [comment]
I have created a new pull request to merge the data with AIRAC 2201.

**Comment by BeaconSlash** [comment]
Created new pull request in to AIRAC 2201, added region and division information as well.

**Pull request closed without merging**
