### PR TITLE
Update RKRR_A_CTR (for south korea)

### PR DESCRIPTION
**Pull request by lancard**
RKRR_A_CTR (all control) covers RKDA and RKRR

### CODE REVIEW

**Comment by NelisV** [comment]
Hey @lancard, you are not on our approved list for korea. Have you followed the procedure to get approval?

**Comment by lancard** [comment]
I'm ATM staff of VATKOR (Sung-ho Kim) - VATKOR3. if you need approval email, could you tell me the email address?

**Comment by lancard** [comment]
refer this site(vatsim korea division): https://www.vatkor.net/xe/intro_staff

**Comment by Adrian2k** [comment]
The email is on the project front page - https://github.com/vatsimnetwork/vatspy-data-project#readme

**Comment by lancard** [comment]
sent email.

**Comment by NelisV** [comment]
Not received it yet. @lancard

**Review by NelisV — APPROVED** [review]

**Review by Adrian2k — APPROVED** [review]

**Pull request merged**
