### PR TITLE
EDGG Sector Changes

### PR DESCRIPTION
**Pull request by Frenkii**

### CODE REVIEW

**Review by Adrian2k — APPROVED** [review]

**Review by NelisV — CHANGES_REQUESTED** [review]
image
Small gap introduced just north of EDGG-G. If you fix that one we can approve it. Rest looks good! Great to see more people using some sort of GIS tool to make these changes :)

**Comment by Frenkii** [comment]
That should fix the gap.

BTW @NelisV which Program do you use? actually I'm not using a tool but seaching the coordinates manually via GNG and Maps :(

**Comment by NelisV** [comment]
Hey @Frenkii i'm using QGIS, open source GIS program. Combined with some python I wrote to convert the files to geojson: https://github.com/NelisV/vatspy-geojson

**Review by NelisV — APPROVED** [review]
Looks good!

**Pull request merged**
