### PR TITLE
Add ZNY low and TRACON boundaries

### PR DESCRIPTION
**Pull request by ajying**
Adds map boundaries for ZNY low sector shelves and PHL and NY TRACON to reduce pilot confusion on who controls various airports underneath ZNY, ZBW, and ZDC.

### CODE REVIEW

**Review by NelisV — CHANGES_REQUESTED** [review]
Geometry wise it looks good, it does need to be brought up to date to airac2013 before we can merge.
You could also consider 'streamlining' or simplifying the geometry above new jersey a little bit, this might confuse people since there is currently no way to clearly show vertical splits.

**Comment by ajying** [comment]
So I merged the most up-to-date branch into it, but I'm not entirely familiar with GitHub so it's still showing more changes than there actually are. Not sure how to fix that

**Review by ajying — COMMENTED** [review]
Up-to-date with 2014

Simplified boundaries for PHL and N90 over New Jersey

**Review by NelisV — APPROVED** [review]
looks good, you could still add sector names in vatspy.dat if you want though: 
image
up to you :)

**Comment by ajying** [comment]
Hmm, they should be in there. I'm seeing
```
KZNY-BDA|New York - Bermuda TMA|BDA|KZNY-BDA
KZNY-CFB|New York - Binghampton (SFC-170)||KZNY-CFB
KZNY-IPT|New York - Williamsport (SFC-100)||KZNY-IPT
KZNY-N90|New York TRACON (SFC-190)||KZNY-N90
KZNY-PHL|Philadelphia TRACON (SFC-130)||KZNY-PHL
```
in the VATSpy.dat diff.

**Comment by Adrian2k** [comment]
Yup they are there, Niels probably didnt load the VATSpy.dat file.
image

**Review by Adrian2k — APPROVED** [review]

**Comment by NelisV** [comment]
ah jup, seen. my bad 😅

**Pull request merged**
