### PR TITLE
Middle East Sectorization

### LINKED ISSUE #135: Subdivisions OMAE
As requested by @chrissKLO 
ACC South East = OMAE_R_CTR
image

### PR DESCRIPTION
**Pull request by chrissKLO**
Fixes #135 and amends neighbouring areas such as OIIX, OBBB. OOMM for the changes surrounding OMAE. Addition of OOMM Sectors which also amends lines between OOMM + VABX/VABF.

### CODE REVIEW

**Comment by Adrian2k** [comment]
Is there a need for all these splits to be shown? Are they common splits? Seems a bit excessive, and messy.

**Comment by chrissKLO** [comment]
All splits are used believe it or not so it would be beneficial that is included in the next set of AIRAC updates.

**Review by Adrian2k — APPROVED** [review]

**Review by NelisV — CHANGES_REQUESTED** [review]
Hey Chris, 

some overlaps/gaps, if you can fix those we can approve this. 
image

**Comment by Adrian2k** [comment]
AIRAC date next week, can you fix the errors Niels spotted by then @chrissKLO?

**Review by NelisV — CHANGES_REQUESTED** [review]
Hmm @chrissKLO we went from 327 changes to 13k 😅. Can you have a look?

**Comment by chrissKLO** [comment]
> Hmm @chrissKLO we went from 327 changes to 13k 😅. Can you have a look?

Ops lemme take a look

**Comment by Adrian2k** [comment]
@chrissKLO any progress here?

**Comment by chrissKLO** [comment]
Recently lost all data on my HDD after it needed to be reformated. Not entirely sure when I can get this sorted. If someone is willing to contact me and get the sector diagrams and do them I would be able to do that.

**Comment by Adrian2k** [comment]
Closing this PR then, feel free to open a new one at a later time.

**Pull request closed without merging**
