### PR TITLE
UKR_CTR Change

### PR DESCRIPTION
**Pull request by dsolesvik**
Changed from UIR to CTR and added the UKR sector. In addition, fixed minor boundary bugs. 

image

### CODE REVIEW

**Comment by meltinglava** [comment]
`git fetch upstream` followed by `git rebase upstream/master` should fix this.

**Comment by dsolesvik** [comment]
conflicts fixed

**Comment by Adrian2k** [comment]
> conflicts fixed

We again have about 30k changes. Did you base your change on the master branch or the airac-2109 branch? If you based it on the master, the issue might be the merge branch of airac-2109 you made.

**Comment by Adrian2k** [comment]
I am the one who broke everything to begin with, I will restore the changes in a new PR.

**Pull request closed without merging**
