### PR TITLE
Addition of LGGG-U

### PR DESCRIPTION
**Pull request by nakoale**

### CODE REVIEW

**Comment by Adrian2k** [comment]
Is this the same FIR boundary as LGGG? If so, just add the following entry to VATSpy.dat:

LGGG|Name of sector|LGGG-U|LGGG

There is no need to have two exactly the same sectors, just for a level split. VATSpy is not designed to show level splits, level bases can be included in the controller info of controllers.

**Comment by nakoale** [comment]
yes it has the same borders like LGGG. how will the pilot see that LGGG-U is online from the moment it's not included in the .dats?Moreover LGGG-U may be the only CTR online without LGGG (e.g overflights for an event) , so it should be shown on vatspy.

**Comment by Adrian2k** [comment]
> yes it has the same borders like LGGG. how will the pilot see that LGGG-U is online from the moment it's not included in the .dats?Moreover LGGG-U may be the only CTR online without LGGG (e.g overflights for an event) , so it should be shown on vatspy.
> 
> So you can keep only the vatspy.dat and add the line you wrote above it should be perfect for us, without adding smth in the FIR.dat.

If you add the line as I referenced above, it will display LGGG as active when LGGG-U_CTR is online, even if it's online alone. It will also then display "Athina-(Above FL325)" as the text. This is how all the US ARTCC area's is able to logon with 2 and 3 letter codes (NY_CTR for example), even though their ICAO is 4 letter such as KZNY.

**Comment by nakoale** [comment]
ok that's understood. so what do i have to do now in order to be an update for the vatspy. reupload the vatspy.dat and then you merge it?

**Comment by Adrian2k** [comment]
@nakoale Since we have two PR's I will close this one PR as we do not need any changes in the FIRBroundaries file.
So reupload the vatspy.dat file with the correct changes in the #315 PR.

**Pull request closed without merging**
