### PR TITLE
Fixed UHMM FIRs boundaries + deleted UHPP FIR

### PR DESCRIPTION
**Pull request by theShpuntik**

### CODE REVIEW

**Comment by NelisV** [comment]
Hey @theShpuntik you are not on our approved list, did you follow the procedure to get approval for your FIR? described in our readme.

**Comment by theShpuntik** [comment]
392C501C-98EF-4EED-BDAD-15E9999BC502

**Comment by NelisV** [comment]
> 392C501C-98EF-4EED-BDAD-15E9999BC502

Hey, all good, managed to find an issue in my mailbox. It's all sorted.

**Comment by theShpuntik** [comment]
Thx

**Review by NelisV — CHANGES_REQUESTED** [review]
This seems to have some rounding issues + an edit to the last line of the file, can you have a look and fix?

**Comment by theShpuntik** [comment]
i dont understand

**Review by theShpuntik — COMMENTED** [review]
fixed another moment

**Comment by Adrian2k** [comment]
The file has a conflict that needs to be resolved.

**Pull request closed without merging**
