### PR TITLE
Update WIIF & WSJC new FIR Boundaries

### PR DESCRIPTION
**Pull request by amosngSP**
## Description of changes

Updates the Jakarta (WIIF) & Singapore (WSJC) FIRs based on the FIR Realignment Agreement.

## Reason and motivation

So that pilots are aware of the new FIR boundaries in place.

## Approved contributor?

- [ ] I am on the approved contributors list
- [ ] I have sent an request by email to get approved
- [X] Someone on the approved contributor list will review this request
**The staff members of Singapore and Indonesia are not approved, but I am approved if that helps?

### CODE REVIEW

**Review by jojo56710 — APPROVED** [review]

**Comment by amosngSP** [comment]
Pending Singapore vACC's approval.
@jojo56710 has approved on behalf of Indonesia vACC

**Review by Cinogard-DS — APPROVED** [review]

**Comment by amosngSP** [comment]
@Cinogard-DS has approved on behalf of Singapore vACC.

**Comment by amosngSP** [comment]
One more minor change made: WAAF, WIIF to use suffix "Control" for their callsign. WSJC uses suffix "Radar" for their callsign.

**Comment by amosngSP** [comment]
Appreciate if the update for this isn't delayed further, as the changes had already taken effect AIRAC cycle 2403. Thanks :).

**Review by NelisV — APPROVED** [review]

**Pull request merged**
