### PR TITLE
April Additions

### PR DESCRIPTION
**Pull request by gdonohoe**
- Created 'EGPX-D' FIR to highlight boundaries for 'SCO_D_CTR' and relative position for 'STC_CTR' on the network. 

- Renamed BGGL FIR to it's new name 'Nuuk'

-  Added missing Cape Verdean Airports

### CODE REVIEW

**Comment by neliscoet** [comment]
Hi,

Please rename FIR FVHA to FVHF and Airport FVHA to FVRG

Also make sure that it is changed in AFRS FSS Station.

Thanks

**Comment by gdonohoe** [comment]
Updated Harare FIR Identifier and Harare International Airport.

**Comment by neliscoet** [comment]
Hi, Not everything is updated. FVHA Harare International Airport is now, FARG Robert Mugabe International. And the FIR FVHA is incorrect. The FIR is FVHF and not FVHA.  I think hence the confusion. FVHF Center and the airport FVRG (old Harare airport)

**Comment by gdonohoe** [comment]
> Hi, Not everything is updated. FVHA Harare International Airport is now, FARG Robert Mugabe International. And the FIR FVHA is incorrect. The FIR is FVHF and not FVHA. I think hence the confusion. FVHF Center and the airport FVRG (old Harare airport)

Hello,

The changes you requested have been made and a request to merge them has been created - I cannot do this I'm afraid. Once they have been reviewed someone will merge them into the main files for you to download.

**Comment by neliscoet** [comment]
thanks mate

**Pull request merged**
