### PR TITLE
Updates to South Sudan

### LINKED ISSUE #501: NEA: Updated FIRs and sector splits
Hi,

I compiled a list of changes for East Africa to include IRL sector splits and to show updated FIRs for Sudan (HSSS) and South Sudan (HJJJ).

_Note: (HJJJ_CTR) only goes up to FL245 anything higher is controller by Khartoum South (HSSS_S) from FL245-999_

[NEA-Updated Sectors.txt](https://github.com/vatsimnetwork/vatspy-data-project/files/8037805/NEA-Updated.Sectors.txt)

Thanks!

### PR DESCRIPTION
**Pull request by amosngSP**
Added HJJJ FIR, Callsign "Juba Control"
Changed all HJ** Airports FIR to HJJJ from HSSS

@chrissKLO @NEAvACC
For your guys approval :)

Resolves #501

### CODE REVIEW

**Comment by amosngSP** [comment]
The first 6 commits were merged long time ago.. No idea why it's still showing up here.
Only the last 3 (3decd89, 4a1427, f18e0ec) are relevant

**Review by Adrian2k — APPROVED** [review]

**Review by NelisV — CHANGES_REQUESTED** [review]
This does  not seem to render properly, Github doesn't recognize it as valid geojson and QGIS has similar issues. Can you have a look? Can't approve it like this.

**Comment by amosngSP** [comment]
Fixed, no idea what happened

**Comment by amosngSP** [comment]
My bad, file name fixed 😂

**Review by NelisV — APPROVED** [review]
Looks good, thanks

**Pull request merged**
