### PR TITLE
Fix CZQM/CZQX polygons and extensions

### LINKED ISSUE #175: CZQM and CZQX are separated by incorrect geometry
A polygon is used as a line to split these 2 sectors, the correct way to do it would be to split it into 2 complete polygons to overlay the 2 sectors (CZQM and CZQX) that already cover both sectors. 

image
So turn this:
image
Into this:
image

### PR DESCRIPTION
**Pull request by ajying**
Fixes #175 

- Change CZQM and CZQX main and extension boundaries to both be polygons and show high-altitude airspace coverage
- Align CZQX, CZQO, EGGX extension, and ZWY boundaries to correct airspace delegation

Requires Moncton/Gander to double-check boundaries and test that they light up correctly.

### CODE REVIEW

**Comment by ajying** [comment]
CZQM Only
CZQM

CZQX Only
CZQX

CZQM + CZQX
CZQMCZQX

CZQM + CZQX + CZUL
CZUL

**Comment by Adrian2k** [comment]
I see this is still a draft, AIRAC 2014 is just in a few days, is this ready to be reviewed?

**Comment by ajying** [comment]
> I see this is still a draft, AIRAC 2014 is just in a few days, is this ready to be reviewed?

I'm still discussing with Mark, the ZQM/ZQX FIR Chief, so it's no ready yet, we can push to 2101.

One question we do have is is there a standards guide for what's allowable and not allowable for FIR boundaries? The original issue this is addressing (on top of fixing the airspace) is that a line was drawn using the FIR polygon instead of drawing a polygon. There are multiple airspace shelves that we want to display but each FIR definition can only accept 1 FIR extension, so are overlapping lines to connect different shelves allowed (not necessarily self-intersections).

**Comment by NelisV** [comment]
the main aim is to make sure you are using correct geometry. This datafile exists solely of polygons, so 'cheating' that system to draw a line is not allowed. Layering multiple polygons on top of each other is. you can have a look at London for instance as an example. Let me know if you have a concrete plan of how you want to tackle this and i can comment a bit more on the specifics. 

image

**Comment by ajying** [comment]
> the main aim is to make sure you are using correct geometry. This datafile exists solely of polygons, so 'cheating' that system to draw a line is not allowed. Layering multiple polygons on top of each other is. you can have a look at London for instance as an example. Let me know if you have a concrete plan of how you want to tackle this and i can comment a bit more on the specifics.
> 
> image

That's what I figured, I'll check back with Mark to see what he wants given the limitations.

**Comment by ajying** [comment]
@Adrian2k I'm not familiar with the intricacies of git, is there any reason why adding airac-2014 to master was its own commit rather than merging the branch in? It's broken the commit history and I'm unable to merge airac-2101 into this branch now to get the diffs to line up correctly.

**Comment by ajying** [comment]
Diff issue resolved.

Ready for review, the update has been approved by Mark Walsh from CZQM/CZQX

**Review by NelisV — APPROVED** [review]
Nice work here, geometry is valid and everything matches up nicely. 👍

**Review by Adrian2k — APPROVED** [review]

**Pull request merged**
