### PR TITLE
VATPRC Update 2113

### PR DESCRIPTION
**Pull request by XCSWxcsw**
image

AIRAC 2113 has a large-scale CTA adjustment in mainland China
- Update almost all currect CTAs
- Remove ZYTL-AR03, ZLXY-H, ZWAK CTAs
- Remove outdated airports

The modification involving non-VATPRC airspace is a repeated boundary, without any modification to the actual airspace.

### CODE REVIEW

**Review by NelisV — CHANGES_REQUESTED** [review]
This causes a gap between ZHWH and ZSOF, could you take a look?
image

**Comment by XCSWxcsw** [comment]
@NelisV done ：）

**Review by Adrian2k — APPROVED** [review]

**Comment by NelisV** [comment]
@XCSWxcsw ah oops, must've missed these in my first review, but there are 2 more. this first fix looks good 👍🏻 
image

**Comment by XCSWxcsw** [comment]
@NelisV ohje that must be from a long time ago. I haven’t change that area. But no worries. I will change it tomorrow morning.

**Comment by XCSWxcsw** [comment]
@NelisV I checked these two points, it is a straight line, so it is not necessary to add again, I removed it XDXD

**Review by NelisV — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
