### PR TITLE
Update LOVV

### PR DESCRIPTION
**Pull request by seelenkrieger**
Addet Main LOVV Sectors

### CODE REVIEW

**Comment by Adrian2k** [comment]
Hello.

We have previosuly rejected sub setors for LOVV for the same reason I am going to partically deny this.
To avoid map cluttering, we are not including sectors we concider as "event sectors" (sectors that are rarely used outside events).

While I know some sectors such as LOVV_C is used considerably much and weekly, we are willing to approve those, however not 15 sectors like you have provided here.

**Comment by jakobeng1303** [comment]
Hi Adrian,
on behalf of Patrick, who spent a lot of time doing this, myself and vACC Austria I feel the need to clarify some things.

I understand that vatspy should not be cluttered with many sectors but this update would include the depiction of 5 ACC sectors which are not only the borders of our horizontal CTR sectors but also equivalent to our local approach units. And while the latter does not serve a relevant purpose on vatspy, it does so in other applications. 

[https://cdn.discordapp.com/attachments/693871045995921408/1017123207578406974/unknown.png](https://cdn.discordapp.com/attachments/693871045995921408/1017123207578406974/unknown.png)

As you can see from the screenshot, the lines added are are really not too cluttering for the eye - at least not more than equivalent lines in other FIRs around us - and luckily all 6(!) not 15 CTR we would like to depict can be just shown with essentially one horizontal and 2 vertical lines (very broken down).

In regards to the actual use, you are right that 1 or 2 of the implemented positions are not very active (mostly LOVV S and sometimes E CTR) but not implementing them would not allow for a depiction of the sectors with less lines. The borders remain the same, the CTR positions shown are just slightly different in their shape. 
For us the combination of N/E/W or NE/B or NE/W is one we open 2-3 times a week and therefore not just for major events but also our weekly event, and many evenings beyond that. They are also used for general sessions, training and solo endorsements, they are by no means just event positions but allow us to - as flexible as Vatsim will allow - change sectorisation on the fly to accommodate changes in traffic flow. 

I understand previous requests, mostly in regards to borders in the Innsbruck region, have been denied but showing accurate sector would very much improve pilot awareness, and as we can now display sectors with the actual borders, I would indeed say things have changed a lot!

Although LOVV is a free route airspace, our routings through LOVV are very much adapted to these sectors. Whether someone has to call LOVV_x_CTR or not is not very clear without a map to show. Avoiding unnecessary calls to figure out the correct frequency would alleviate sector frequency load significantly. 

Furthermore, departures and arrivals at no less than 2 major and 4 (what will be) restricted minor airports would get an accurate indication of controlled airspace or not, which we hope would reduce no contact pilots and wrong calls. 

Maybe you could reconsider and allow us to proceed? 

Regards,
Jakob

**Comment by Adrian2k** [comment]
Apologies. I did not have time to actually check the files when I was reviewing the latest pull requests so we could push a AIRAC released. I only checked the reference of how many new lines were added (with the assumption that one line = one sector) forgetting that they have to be added to 2 files.

Now that I actually have had time to look on the files, I can see the following 8 sectors:
LOVV-B
LOVV-C
LOVV-E
LOVV-F
LOVV-N
LOVV-S
LOVV-W
LOVV

LOVV-S and LOVV-F barely has any hours logged this year - 12hrs and 2 hrs.
LOVV-W and LOVV-E also has not alot of hours compared to the others - about 30 hrs each.

The decitions on what to include or not is not made by me alone, however I am quite sceptical of including LOVV-S and LOVV-F. It will highly go against our policies and other VACC's who we have denied previously will be complaining quite a lot.

**Comment by Alpi-no** [comment]
Hi Adrian,

Thank you very much for reconsidering our proposal. I. Understand the premises of decluttering the map but I would also like to highlight that adding sectors like LOVV S/F is not cluttering the map in any additional way because the line‘s already exist (and have to for the other splits), we just give them another additional purpose in a different combination.

As we also plan to change our callsigns to - instead of _ , it should very clear depending on the split which sector is active or not, regardless of any other lines displayed, which should in my opinion be the best option to combat clutter - except for implementing vatglasses in the near future ;) 

You are right that both LOVV S and F used to be much more common in the past and I think not including them if required by your policy or maintaining fairness, despite not cluttering the map as said before, should not be a problem for us. 
Not including E/W will by problematic however, and slightly defeating the purpose of this update as N-E-W is our primary 3 man split and with 50-ish hours with our relief callsigns included is not too little for a small FIR and vACC like hours to include in my opinion.

Maybe we could find an agreement that includes E and W CTR but omits F and S if necessary? 

Regards, Jakob

**Comment by Alpi-no** [comment]
Hi Adrian, 
any updates? As we have quite the Event this weekend (https://vatsim.net/events/Finally%20Austria%202022%20-%20Day%201), I'd love for the changes to be implemented. We will have some splits active that would benefit greatly from the Vatspy update. 
Regards, Jakob

**Comment by Adrian2k** [comment]
Just to verify, the idea is still to only use for example LOVV_B_CTR as logons? Not LOVV-B_CTR?

**Comment by Alpi-no** [comment]
Hi Adrian, there are still 1 or 2 technical issues to resolve before we can make that decision but we would love to have it implemented already, reagrdless whetehr we implement now or next Airac.
- Jakob

**Comment by Adrian2k** [comment]
For now, I will approve all but F and S to comply with our policies.
We can come back to F and S at a later date.

**Comment by Alpi-no** [comment]
roger, thank you!

**Review by Adrian2k — APPROVED** [review]

**Review by NelisV — APPROVED** [review]

**Pull request merged**
