### PR TITLE
Update ZMA/ZMO boundaries

### PR DESCRIPTION
**Pull request by erikquinn**
Add basic depiction of ZMA & MYNN_CTR shelving ~~as well as adjacent approach control airspace between ZMA/ZJX/MYNN so people will hopefully stop calling the wrong one of us~~. 😄 Also updates ZJX and ZHU coordinates to match the coordinates _shown in their sector files in addition to ours_.

Changes depicted below:

ZMA Before:
image

ZMA After:
~~[with approach controls](https://user-images.githubusercontent.com/5103735/108130244-5a1cec80-707d-11eb-8fef-5611a301c297.png)~~
image

ZMA After (ZJX online):
~~[with approach controls](https://user-images.githubusercontent.com/5103735/108130701-14acef00-707e-11eb-8d96-a9a4c5997440.png)~~
image

ZMA After (ZMA online):
~~[with approach controls](https://user-images.githubusercontent.com/5103735/108130889-5d64a800-707e-11eb-89ab-11578c5f0461.png)~~
image

ZMA After (ZMA & ZJX online):
~~[with approach controls](https://user-images.githubusercontent.com/5103735/108130819-445bf700-707e-11eb-839e-3a57c043c493.png)~~
image

Airspace delegation in the area (from ZMA SOP):
image

ZMO Before:
image

ZMO After (MYNN online):
~~[with approach controls](https://user-images.githubusercontent.com/5103735/108130575-e16a6000-707d-11eb-8aa5-26e33b0637ac.png)~~
image

ZMO After (ZMO online):
image

ZMO After (ZMO & MYNN online):
image

ZMA/ZMO/MYNN all online:
image

### CODE REVIEW

**Review by NelisV — CHANGES_REQUESTED** [review]
Hey Erik, we discussed this internally, but we don't want to go down the route of adding approach sectors as 'FIR's', Vatspy wont light them up, and it'll clutter the map further. Adjusting the border between Jacksonville and Miami is fine tho.

**Comment by erikquinn** [comment]
@NelisV Alright, I thought that might be the case, but since I saw ZNY with IPT/PHL/CFB/N90 depicted, I figured it would be a good opportunity to do the same so people will be able to determine which center to call.

I'll remove the approach control depiction.

**Comment by prryplatypus** [comment]
Main reason for this is to avoid cluttering the maps with information that's not necessary. If all (sub)divisions did the same we would end up with a pretty nasty-looking online map, where most of the sectors would never be lit up. While there is indeed sectors already depicted in the data we are distributing, I believe this data was there from before this repo was centralised.

If/when VATSPY supports defining approach sectors accurately we will reconsider the decision we are taking for now.

**Comment by erikquinn** [comment]
@prryplatypus Oh, for sure. To be honest, I kind of expected it, but just figured I'd throw it out there and see what you all said since there was a precedent for it with ZNY. I agree it would make the map pretty messy, and it's also super hacky/clunky given that the shape drawn isn't what will light up when the approach comes online anyway, nor should you associate the approach control airspace with the center airspace. So I totally agree.

If the day comes where approach control boundaries can be added as their own facilities with boundary coordinates rather than the teal circle, that's when the real party will start 😉

All finished with the requested changes and a new set of screenshots generated.

**Review by prryplatypus — APPROVED** [review]

**Comment by Jeeveegee** [comment]
I'm slightly concerned that this new layout will cause confusion for pilots when only KZMA is online? KZMA now seems to cover a few islands and airports (including MYGF, one of their bigger ones) in the Bahamas.

You picked the High Boundary to depict the border between KZMA and KZMO, instead of the Low Boundary between KZMA and Nassau, as can be seen on this image from the Miami/Nassau LOA.



Wouldn't it make more sense to stick to the Low Boundary between KZMA and MYNN and avoid the confusion?

**Comment by erikquinn** [comment]
@Jeeveegee Totally agree, it will probably _increase_ the nuisance calls we get from people requesting clearance from MYGF and even MYNN-- hence my original proposal ([img](https://user-images.githubusercontent.com/5103735/108130244-5a1cec80-707d-11eb-8fef-5611a301c297.png)) of labeling the approach controls, so it was very clear what was and wasn't ZMA. It was decided to avoid going this direction to minimize map clutter (a worthy and understandable goal).

ZMA also experiences the opposite case frequently-- pilots who say "I'm leaving your airspace, switching to unicom now" when they really aren't, or as an inbound refusing to contact us "because I'm not in your airspace yet" when they're 40 miles deep into it-- and all because the high boundary is not shown at all. All of that confusion would be resolved by depicting the high boundary. So it's a tradeoff.

Similarly, all the same problems exist with _ZMO_... sometimes people contact ZMO for top-down service at MYGF/MYNN/MYEF/MYAM/MYAT/MBPV/etc even though it's beneath ZMO airspace. With ZMO, there isn't really a good way (with the current functionality of vatspy and guidance from the data project here) to depict who owns what when there is shelving or airspace split vertically. I would wager that ZMA is the same as ZMO in that the people who know not to call us will continue not to, and those who don't will likely do it either way.

If we used the low boundary exclusively, then ZMA/ZMO have all the same issues with pilots thinking there's this 200nm gap between ZMA and ZMO, when in actuality, with Nassau offline, they literally border each other. So we went with the implementation of "if you own any altitude here, light it up". That way, when ZMA/ZMO/MYNN are all on, you can see (like in the last image above) where a vertical split exists, which I hope would reduce pilot confusion. Once a new pilots gets the idea of "Nassau does the top-down", they'll be able to predict that if MYNN_CTR is offline and their airport is within the MYNN_CTR boundary, they can expect ZMA/ZMO to send them to unicom. So maybe it's more clear, maybe it's less (I personally think much _more_), but at least now there is more accurate information for them to interpret. 🤷‍♂️ 

_Really_, I'd like to see a way to provide more detailed depictions of airspace, but in the absence of that, I figured this was about the most accurate picture I could portray within the constraints of what is possible/permitted. 😃

**Review by Adrian2k — APPROVED** [review]
@NelisV will also have to approve this, just to double-check the FIR boundaries are correct.

**Comment by Jeeveegee** [comment]
Only request I have is to move the letters KZMO back to the right, not right above the letters MYNN. We're implementing the Caribbean Control at the moment, and those UIR tags are gonna overlap the FIR tags.

**Comment by erikquinn** [comment]
@Jeeveegee I took your request to the senior staff and they concur with my assessment that moving the KZMO label into "the area that's purely KZMO" would not be advisable, as it would be interpreted as showing that the Provo extension is MYNN_CTR exclusively, with ZMO filling in around it. Leaving the marker above the MYNN_CTR marker much more clearly depicts that both facilities own a portion of that area.

I had a look at the changes you mentioned about CARI/CARE/CARW (which btw will cause _severe_ confusion, as it will say `covers MYNN above FL245`, which isn't true if ZMO is on, or `covers ZMO above FL245` when MYNN_CTR is on, and various other untruths)... Regardless, that's above my paygrade, and in light of the existence of a UIR tag above MYNN, we have shifted the labels to leave room for them. The below screenshot is zoomed very far out and shows enough space for it to be clear. (ignore the fact that it says `ATL` obviously, it's the only way I could get it to light up for a picture 😉)

image

**Comment by Jeeveegee** [comment]
@erikquinn Thanks for making the changes, looks fine to me, leaving enough space like that. 

Just FYI we're fully aware that the Caribbean FSS UIR tags might make things more confusing when the underlying sector like MYNN or KZMO are online together with the FSS. You can see this happen almost daily in Europe with Eurocontrol. In the end MYNN and KZMO (or any other VATCAR FIR for that matter) always take priority over the FSS, obviously. Sadly this is just the way vatspy works as of right now and we have no other way of showing it.

**Review by NelisV — APPROVED** [review]
Nice to see this is sorted out. Geometry wise i've got nothing to complain. Thanks all for your work here!

**Pull request merged**
