### PR TITLE
VATSpy Sectors + Airports Update (India)

### PR DESCRIPTION
**Pull request by nickelwarrior**
## Description of changes

- Complete realignment of all FIR boundaries and ACC sectors taking into consideration neighbouring FIR boundaries as per data from Indian eAIP
- Drawn the border of VECF/VEGF and VYYF as per Navigraph navdata
- Upper Area sector splits added for all FIRs along with _UAC_CTR positions which exclude Oceanic airspace and only include the Upper Area control boundaries in the bandbox
- Lower Area control sectors of VILK (Lucknow), VIJP (Jaipur), VIUX (Udhampur) as well as Lower Delhi ACC splits (VIDF UDP1-4) added for VIDF
- Lower Area control sectors realigned as per eAIP in VOMF, along with addition of VOBG (HAL) sector which covers up to FL460
- Lower Kolkata ACC splits (VECC-N/E/W) addedMumbai ACC (U5) added which covers a portion of Oceanic airspace + Airspace west of Ahmedabad ACC, with radar coverage
- All Indian airports data added/updated as per ourairports.com 

## Reason and motivation

We are moving away from the system of covering entire FIRs under one callsign and instead only controlling the portion which is served by surveillance coverage (eg, VOMF_UAC_CTR) under Upper Area Control of the respective FIR. This helps increase realism because IRL, for example, the northern part of Delhi FIR is not controlled by Delhi Control but instead Udhampur ACC (VIUX_CTR) which provides FIS from GND/UNL. So after this update, only UAC will get highlighted instead of the entire FIR. This also helps in ensuring that controllers control only the relevant sector during events instead of opening the entire bandbox which will overload the controller. This also allows multiple controllers to staff up Upper sector splits and thereby increase immersion and reduce workload.

We are also using the latest VATSpy features in ensuring that the uncontrolled sectors remain hidden and only pop up when being controlled, in order to avoid unnecessary clutter on the map. This update will also help us ensure that the correct airspace is being highlighted on VATSpy and Simaware and avoid any confusion regarding actual AoR as shown in Euroscope vs VAT-Spy. 

## Approved contributior?

- [ ] I am on the approved contributers list
- [ ] I have sent an request by email to get approved
- [X] Someone on the approved contributer list will review this request

### CODE REVIEW

**Comment by Adrian2k** [comment]
Is this an AIRAC related update or has this already been operationally implemented?

**Comment by nickelwarrior** [comment]
The FIR/ACC boundaries have been incorrect since the very beginning. The Upper Area sectors for VOMF have been implemented in the sector files very recently, and will be implemented in the sector files for the other FIRs very soon. 

The airports are a combination of fixing incorrect coordinates, missing IATA, removal/renaming of old ICAO and addition of new airports as per latest AIRAC.

Regards,
ACCIND2

**Comment by VATWAOps** [comment]
Implementation received and is currently under review by Division Staff. Will revert back at a later date.

Brodie M. VATWA2

**Comment by VATWAOps** [comment]
> > Implementation received and is currently under review by Division Staff. Will revert back at a later date.
> > Brodie M. VATWA2
> 
> Any update on this @VATWAOps

Hi, Division is in the final stages. Will revert back before the next cycle update

**Comment by AviatorRoyal** [comment]
@VATWAOps  any update?

**Comment by Adrian2k** [comment]
Please open a new PR when changes are done and ready for implementation. Closing this PR.

**Pull request closed without merging**
