### PR TITLE
Update VATSpy.dat

### PR DESCRIPTION
**Pull request by nakoale**
Radar instead of Control. Subsectors' name.

### CODE REVIEW

**Comment by nakoale** [comment]
changed all LGGG/LCCC subsectors to LGGG-X instead of LGGGX

**Comment by nakoale** [comment]
LLSC sector inserted. It existed in Vatspy.dat but not in FIRBoundaries.dat

**Review by Adrian2k — CHANGES_REQUESTED** [review]
`LLSC|Tel Aviv South Control||LLLL`

This one would need to be changed if you want to make LLSC to its own FIR.
It currently shows LLLL as active when LLSC is online:
image

**Comment by nakoale** [comment]
it is already impemented in the latest FIRboundaries.dat i uploaded. So it will show LLSC as it should ;)

**Comment by Adrian2k** [comment]
> it is already impemented in the latest FIRboundaries.dat i uploaded. So it will show LLSC as it should ;)

Your VATSpy.dat must the following line:
`LLSC|Tel Aviv South Control||LLLL`

to

`LLSC|Tel Aviv South Control||LLSC`

I can not see you have ammended this line accordingly.

**Comment by nakoale** [comment]
we all need to wait until one of the developers approves the changes. only then the data is updated. we just send the changes.

**Comment by nakoale** [comment]
> 
> 
> > it is already impemented in the latest FIRboundaries.dat i uploaded. So it will show LLSC as it should ;)
> 
> Your VATSpy.dat must change the following line:
> `LLSC|Tel Aviv South Control||LLLL`
> 
> to
> 
> `LLSC|Tel Aviv South Control||LLSC`
> 
> I can not see you have ammended this line accordingly.

it is ammended. take a closer look.

**Comment by Adrian2k** [comment]
> > > it is already impemented in the latest FIRboundaries.dat i uploaded. So it will show LLSC as it should ;)
> > 
> > 
> > Your VATSpy.dat must change the following line:
> > `LLSC|Tel Aviv South Control||LLLL`
> > to
> > `LLSC|Tel Aviv South Control||LLSC`
> > I can not see you have ammended this line accordingly.
> 
> it is ammended. take a closer look.

image

I still see it as LLLL?

**Comment by Adrian2k** [comment]
Your latest upload fixes it, perfect.

**Comment by nakoale** [comment]
You are totally right Adrian. Just saw it. FIXED

**Comment by prryplatypus** [comment]
@Adrian2k Are you happy with this PR now? 😛

**Comment by Adrian2k** [comment]
Seems fine now

man. 21. sep. 2020 kl. 10:40 skrev Néstor Pérez <notifications@github.com>:

**Review by prryplatypus — APPROVED** [review]

**Pull request merged**
