### PR TITLE
THAMES_APP online ring centres on EGLC

### LINKED ISSUE #179: THAMES ring over EGLC
The THAMES_APP online ring should centre on EGLC, its major airport, rather than EGKB

### PR DESCRIPTION
**Pull request by hsugden**
Fixes #179 

The THAMES_APP online ring centres on EGLC, its major airport, rather than EGKB

### CODE REVIEW

**Comment by Adrian2k** [comment]
If you already have not done so, send an email as described on the readme to verify your account.

**Comment by hsugden** [comment]
Did so the other day to a.long@, but it seems the read me has been changed since, so I'll do that again!

**Comment by hsugden** [comment]
Fixes #179

**Comment by mbozwood** [comment]
@hsugden is the UK Ops Director and can be confirmed on the UK sector file repos. Confirmed by VP Dev.

**Comment by prryplatypus** [comment]
Yup, we're maintaining a list with all their email addresses in case there's any doubts about a change at any point; hence the asking them to email me. I've just received Harry's ;)

**Review by Adrian2k — APPROVED** [review]

**Review by NelisV — APPROVED** [review]

**Comment by NelisV** [comment]
fixed #179

**Pull request merged**
