### PR TITLE
Add SCO_N and SCO_S

### PR DESCRIPTION
**Pull request by lennycolton**
SCO_S covers the southern half of SCO_E (Montrose, Humber, Tyne) and SCO_D (Deancross) and is now a standalone split (whilst SCO_E is not a standalone split).

SCO_N covers the northern half of SCO_E (Hebrides, Moray).

Both currently display as SCO_E on SimAware. This is particularly problematic for SCO_S, which covers all of Scotland's major airports (through SCO_D) but currently displays as covering none of them.

### CODE REVIEW

**Comment by Adrian2k** [comment]
Currently the sectors (especially SCO_N) is not in compliance with our policy with new additions of sub-sectors needing to be regularly staffed outside of events.

But with the new VATSpy change that now supports them better, we will take it up for discussion regarding adjusting the policy.

**Comment by lennycolton** [comment]
> Currently the sectors (especially SCO_N) is not in compliance with our policy with new additions of sub-sectors needing to be regularly staffed outside of events.
> 
> But with the new VATSpy change that now supports them better, we will take it up for discussion regarding adjusting the policy.

The default SCO splits are being adjusted. SCO_E is not a standalone split, but SCO_S has been added to the list and is likely to be opened regularly without adjacent control. SCO_N covers the remainder of SCO_E which is not within SCO_S.

**Comment by Adrian2k** [comment]
There will be changes in how VATSpy displays inactive subsectors,  so the addition of subsectors will be approved.

Awaiting Harry's review before we proceed with our review.

**Comment by Adrian2k** [comment]
@hazzas-99 awaiting your review before we proceed with our review

**Review by NelisV — APPROVED** [review]

**Pull request closed without merging**
