### PR TITLE
AIRAC 2102: Changes for Ukrainian airports and positions

### PR DESCRIPTION
**Pull request by megazloj**
I've changed airport names according to the AIP and made a few changes to the position names.

### CODE REVIEW

**Comment by NelisV** [comment]
Hey @megazloj you're not in our list of approved staff. could you verify your position with Néstor through the email process described in the readme? Also check the branch your merging into, the one we're currently working on is 2101.

**Comment by prryplatypus** [comment]
Haven't had time to add him to the list yet, but can confirm he is approved! :)

**Comment by NelisV** [comment]
Oh that's allright then :) @megazloj please comment on the branch tho.

**Comment by megazloj** [comment]
> Oh that's allright then :) @megazloj please comment on the branch tho.

So you want me to pick those commits and apply them to the 2101 branch and then re-create PR?

**Comment by prryplatypus** [comment]
If you're happy with us just switching it to the 2101 branch we can just switch this PR over for you 🙂

**Comment by megazloj** [comment]
> If you're happy with us just switching it to the 2101 branch we can just switch this PR over for you 🙂

If that's not against any contribution rules and won't break anything

**Comment by prryplatypus** [comment]
Changed. Ready for review @NelisV @Adrian2k! :P

**Review by Adrian2k — APPROVED** [review]
The changes seems simple enough

**Review by NelisV — APPROVED** [review]

**Pull request merged**
