### PR TITLE
Update Mexico's ACC to match the new sectors.

### PR DESCRIPTION
**Pull request by gvaldezsan**
This updates the ACCs from Mexico to the reflect the new changes by the aviation authority (AFAC)

Old

image

New

image

### CODE REVIEW

**Review by NelisV — CHANGES_REQUESTED** [review]
Thanks for the commits, this needs some work tho. You are making changes to other FIR's, if you check the files changed section at the top of this PR you can see the spaces added. Please remove those, so you only edit the sectors where you are making changes. 

The borders could also be improved somewhat: 
Southern end of MMEX:
image
A, the borders should intersect, As a result there is some diverging going on towards the south. 
B, gap created due to the 2 extra waypoints. 
C, some unnecessary waypoints.

**Comment by NelisV** [comment]
@gvaldezsan Ping :) any chance to look at this? if not we'll probably close it soon.

**Comment by gvaldezsan** [comment]
@NelisV Sorry I took a LOA and just recently got back. Will fix this weeked!

**Comment by prryplatypus** [comment]
Moved this to next cycle. If not sorted when that one gets released we'll close this PR.

**Comment by Adrian2k** [comment]
@gvaldezsan AIRAC date is the upcoming Thursday, the PR will be closed if its not sorted by then.

**Pull request closed without merging**
