### PR TITLE
FIR indicators of airports

### PR DESCRIPTION
**Pull request by kusterjs**
corrected a number of airports not having a valid (known) FIR indicator
deleted a number of indonesian airports either due to double use of indicator or non-existence (verified with various sources)

### CODE REVIEW

**Review by Adrian2k — APPROVED** [review]

**Review by prryplatypus — CHANGES_REQUESTED** [review]
While I'm happy with the FIR indicator changes, I'm not too convinced about the airport deletions. I've just checked one random airport of those deleted (WRKS), and it [does exist in real life](https://www.greatcirclemapper.net/en/airport/SAU-WRKS-sawu-airport.html). This leads me to think that it is not the only one for which this is the case, and if they're there I want to think it is because they've existed at some point and/or still exist.

Please recheck all of the deletions and lmk when that's done. I'd also recommend submitting 2 different PRs: One for the FIR changes and another for the "cleanup" in order to keep things easy to find and to follow in the future.

**Comment by kusterjs** [comment]
Well, I don't know about the data integrity of your source. I checked each individual airport on skyvector, satellite images and the database provided by LIDO. Also other sources don't seem to know these airports. A search for WRKS brings up www.greatcirclemapper.net and similar pages which seem to use the same database. But there no verified source these airports actually exist. I was even bothering the specialist from my national AIM office and searched the entire AIP of Indonesia. There are no airports published with a designator WR**.

**Comment by marvk** [comment]
I just did some googling of airport names and ICAOs, and it seems like 

[Iskandar Airport](https://en.wikipedia.org/wiki/Iskandar_Airport), now `WAGI` was at one point in time `WRBI`

[Gusti Syamsir Alam Airport](https://en.wikipedia.org/wiki/Gusti_Syamsir_Alam_Airport), now `WAOK` was at one point in time `WRBK`

[Frans Xavier Seda Airport](https://en.wikipedia.org/wiki/Frans_Xavier_Seda_Airport), now `WATC` was at one point in time `WRKC`

[Kalimarau Airport](https://en.wikipedia.org/wiki/Kalimarau_Airport), now `WAQT` was at one point in time `WRLK`

[Umbu Mehang Kunda Airport](https://en.wikipedia.org/wiki/Umbu_Mehang_Kunda_Airport), now `WATU` was at one point in time `WRRW`

I found these by Googling the query `"formerly WR__"` for each ICAO code. It indeed seems like in many places, the `WR` prefeix have been retired in favor of `WA`

**Comment by Adrian2k** [comment]
The WRxx entries does not exist in the Eurocontrol database either.
The new "replacements" as mentioned by marvk above exists in the vatspy database already, on the same locations.

**Review by prryplatypus — APPROVED** [review]

**Pull request merged**
