### PR TITLE
EDMM: update west sectors to new IDs

### PR DESCRIPTION
**Pull request by globin**
## Description of changes
Updates existing and adds new EDMM positions

## Reason and motivation
Callsign and sector changes in EDMM

## Approved contributior?
- [X] Someone on the approved contributer list will review this request (reviewed by @jannikvogel)

### CODE REVIEW

**Review by jannikvogel — APPROVED** [review]

**Comment by Adrian2k** [comment]
I have a feeling that once we merge #739 this one will only go into a conflict with that merge..

@NelisV do not merge this until #739 has been merged.

**Comment by Adrian2k** [comment]
Nevermind - seeing that the other file is in conflict we may want to merge this one first unless it gets resolved quickly.

**Review by Adrian2k — APPROVED** [review]
Awaiting @NelisV review

**Comment by globin** [comment]
Could you merge this soon please, pilots are contacting us all the time from way outside of the sector constantly due to ZUG being displayed over the whole EDMM FIR

**Review by NelisV — APPROVED** [review]

**Pull request merged**
