### PR TITLE
Norway > Polaris

### PR DESCRIPTION
**Pull request by Adrian2k**
5th of November Norway FIR/Control becomes Polaris FIR/Control.

Removed obsolete NOR logons.
Added ENRC (Remote tower) for the future, aliased to ENOR.

No need to merge yet.

### CODE REVIEW

**Comment by prryplatypus** [comment]
Norway --> Polaris, but Polaris > Norway 😏

**Comment by Adrian2k** [comment]
> Norway --> Polaris, but Polaris > Norway 😏

Gonna miss Norway 😢

**Comment by prryplatypus** [comment]
@Adrian2k Confirm this can be merged tonight?

**Comment by Adrian2k** [comment]
Its only 2 hours to the change, you can merge it now if you like.

**Pull request merged**
