### PR TITLE
Added the new OTDF FIR, + surrounding polygon fixed

### PR DESCRIPTION
**Pull request by dsolesvik**
Changes requested by VATMENA1

### CODE REVIEW

**Review by Adrian2k — APPROVED** [review]

**Review by NelisV — CHANGES_REQUESTED** [review]
Like my discord msg: Github nor QGIS want to render this, something seems wrong but i'm not sure what. Can you go back and check your file?

**Comment by NelisV** [comment]
This will shift to next month.

**Comment by dsolesvik** [comment]
Change should be fixed now, was missing a coma at the end of a line :D

**Comment by Adrian2k** [comment]
Resolved the merge conflict.

**Pull request merged**
