### PR TITLE
modified EDMM and EDWW sectorization

### PR DESCRIPTION
**Pull request by jannikvogel**
Hey guys,

would be great if you could implement those sector and station changes for FIRs EDMM and EDWW.

Best regards
Jannik
---
Deputy Chief, EDMM
NAV Chief, EDMM

### CODE REVIEW

**Comment by jskramer909** [comment]
Stations adjusted for EDWW part are looking fine.

Sebastian
NAV Chief EDWW

**Comment by Adrian2k** [comment]
@jskramer909 @jannikvogel Have atleast one of you guys sent an email as described on the project page to get your account approved? I could not find either of your on our approved list for Germany.

If you have very recently sent one then no worries, my list have simply not been updated yet in that case. :)

**Comment by jannikvogel** [comment]
You should have received an email now :) 

Regards
Jannik

**Review by Adrian2k — APPROVED** [review]

**Review by NelisV — CHANGES_REQUESTED** [review]
So looking at the GeoJSON, you copied the EDMM-G sector and called it EDMM-O if i follow correctly? I don't see any new area covered, also the rounding for the new sector seems off. Can't the same result be achieved with changes to VATSpy.dat, without adding an identical polygon?

**Comment by NelisV** [comment]
Ah yeah that makes a bit more sense. I see. Good. Can you however look at the rounding? Round to 6 decimals after the comma.

**Comment by jannikvogel** [comment]
> Ah yeah that makes a bit more sense. I see. Good. Can you however look at the rounding? Round to 6 decimals after the comma.

done:)

**Review by NelisV — APPROVED** [review]
Thanks all! looks good.

**Pull request merged**
