### PR TITLE
Update to VATPAC FIRs and FIR Positions

### PR DESCRIPTION
**Pull request by vatpacais**
Required for AIRAC 2110 to align with sector file updates
Change of FIR frequencies, new positions and new/modified Boundaries to more closely align with real world
Removal of YBBB and YMMM UIRs as per VATPAC Board approval

### CODE REVIEW

**Comment by vatpacais** [comment]
Just checking that this pull request is on track to be included in 2110 as it is a major update to our airspace which has to be synchonised with the release of our 2110 sector files and AFV updates, all prepared for the 2110 release date (7 Oct)

**Comment by NelisV** [comment]
Yeah as mentioned in #417, this introduces all sorts of problems with misaligned borders. I understand that this might be exactly what is in your AIP, but it is just not suitable for a well performing map. You're going to have to make manual adjustments so the polygons properly align. 
image
image
image

**Review by NelisV — CHANGES_REQUESTED** [review]
Yeah as mentioned in #417, this introduces all sorts of problems with misaligned borders. I understand that this might be exactly what is in your AIP, but it is just not suitable for a well performing map. You're going to have to make manual adjustments so the polygons properly align. I can't approve it in it's current state. 
image
image
image

**Comment by NelisV** [comment]
So for my understanding, do you get the exact coordinates of what you push from your AIP? or is this generated from a sector description? If you have some code that generates this data it should be possible to make sure they use shared points to prevent these gaps/overlaps. I will update the readme to make it more descriptive, but in general it's bad practice to have these errors as it will make any apps using the data perform less well. It might not be described exactly but preventing these errors is the direction we've consistently been moving over the past months with this dataset and i don't want to make an exception here. 

It's also in your case not a monthly thing, so taken the time you should be able to manually correct the gaps as @dsolesvik has proven with his fixes to australia. I've written this guide, that might also be useful: https://github.com/NelisV/vatspy-geojson/wiki/Editing-Sector-Files-for-VAT-Spy

**Pull request closed without merging**
